### ISSUE TITLE
All lists are empty

### ISSUE THREAD

**Issue by osirisguitar** [kodi-svtplay/xbmc-svtplay#100]
Add-on doesn't work anymore in Gotham 13.1.

Thanks for the great work on this add-on, let me know if I can do anything to help.

**Comment by linqcan** [comment]
Could you please leave an explanation of what you mean? Preferly, specify all steps needed to recreate this issue.

Edit: Also, which version of the addon are you running?

**Comment by osirisguitar** [comment]
- Search always returns nothing
- All lists like Program A-Ö, Kategorier etc are empty
- Best of SVTPlay works fine, both lists and starting the streams.
- Debug mode says nothing
- No errors are reported by xbmc

I'm running 3.3.5. I reinstalled both XBMC and the plugin without change.

I'm not entirely sure, but now that I think of it I had the same problem over a year ago and fixed it by deleting some files... Are there files left by the addon after uninstall that you could delete manually?

**Comment by linqcan** [comment]
The latest, and supported, version is 4.0.3. Update to that version and let me know if you still have issues.

Note that XBMC 13 is required for the SVT Play addon as of the new SVT Play site release.

**Comment by osirisguitar** [comment]
It's weird, today it's been updated to 4.0.3 and works perfectly. Sorry for the trouble.

**Comment by linqcan** [comment]
Good to hear!
