### ISSUE TITLE
subcategories as input parameter not working?

### ISSUE THREAD

**Issue by nicco11a** [kodi-svtplay/xbmc-svtplay#102]
I can bind a key such as F11 to go directly to a category such as news (nyheter) by using the runaddon call:
mode=ti
url=kategorier/nyheter 

But I can not specify sub categories such as rapport for example:
url=kategorier/nyheter/rapport

I get a general script error without any useful error message from XBMC that the svtplay script died, is this a limit or did I run into a bug?

I am looking for this functionality!

**Comment by linqcan** [comment]
Unfortunately, the URLs are not that logical. The URLs used by the addon is the ones from the web page as the addon is scraping the web page. For example, if you look at  http://www.svtplay.se/nyheter you'll see that "Rapport" has the URL "http://www.svtplay.se/rapport".

So your parameters would be:

```
mode=pr
url=/rapport
```

**Comment by nicco11a** [comment]
Ahh, that works like a charm! 

I noticed the redirect, but tried /rapport in mode ti and failed, thanx for enlightening me about mode pr.

**Comment by linqcan** [comment]
Good to hear.

The addon now features "favorites" that let you "favorite" a program for easy access from the top-level menu (in-case you run out of keyboard bindings :wink: ).

**Comment by linqcan** [comment]
@nicco11a Another thing, I might change these in a future update as the mode names can be more logical now as they are not dependent on the SVT Play site anymore. Will notify you here when/if they change!

**Comment by nicco11a** [comment]
Cool with the favourite option, may use it later.

I appreciate your heads up on changing of module names in the future. It would be nice if you also wrote about it in the readme file / changelog or added a parameter file so people don't have to backtrack the Python code to figure out howto use the input parameters.
