### ISSUE TITLE
Categories doesn't work

### ISSUE THREAD

**Issue by ghost** [kodi-svtplay/xbmc-svtplay#103]
Trying to use Categories and it generates an error.

This is from xbmc.log

22:25:00 T:2996102976  NOTICE: Starting XBMC (13.2 Git:0f3db05). Platform: x86 Linux 32-bit

21:11:35 T:2996102976   DEBUG: LIRC: Update - NEW at 150884724:000000037ff07bdd 00 KEY_OK mceusb (KEY_OK)
21:11:35 T:2996102976   DEBUG: OnKey: 11 (0x0b) pressed, action is Select
21:11:35 T:2996102976   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.svtplay/?mode=categories)
21:11:35 T:2996102976   DEBUG:   ParentPath = [plugin://plugin.video.svtplay/?mode=search]
21:11:35 T:2094484288  NOTICE: Thread JobWorker start, auto delete: true
21:11:35 T:2094484288   DEBUG: StartScript - calling plugin SVT Play('plugin://plugin.video.svtplay/','79','?mode=categories')
21:11:35 T:2094484288   DEBUG: WaitOnScriptResult - waiting on the SVT Play (id=85) plugin...
21:11:35 T:2136447808  NOTICE: Thread LanguageInvoker start, auto delete: false
21:11:35 T:2136447808    INFO: initializing python engine.
21:11:35 T:2136447808   DEBUG: CPythonInvoker(85, /home/thnov/.xbmc/addons/plugin.video.svtplay/default.py): start processing
21:11:35 T:2136447808  NOTICE: -->Python Interpreter Initialized<--
21:11:35 T:2136447808   DEBUG: CPythonInvoker(85, /home/thnov/.xbmc/addons/plugin.video.svtplay/default.py): the source file to load is "/home/thnov/.xbmc/addons/plugin.video.svtplay/default.py"
21:11:35 T:2136447808   DEBUG: CPythonInvoker(85, /home/thnov/.xbmc/addons/plugin.video.svtplay/default.py): setting the Python path to /home/thnov/.xbmc/addons/plugin.video.svtplay:/home/thnov/.xbmc/addons/script.module.pyamf/lib:/home/thnov/.xbmc/addons/script.module.xbmcswift/lib:/home/thnov/.xbmc/addons/script.module.simplejson/lib:/home/thnov/.xbmc/addons/script.module.beautifulsoup4/lib:/home/thnov/.xbmc/addons/script.module.beautifulsoup/lib:/usr/share/xbmc/addons/script.module.pil/lib:/home/thnov/.xbmc/addons/script.common.plugin.cache/lib:/home/thnov/.xbmc/addons/script.module.requests/lib:/home/thnov/.xbmc/addons/script.module.mechanize/lib:/usr/share/xbmc/addons/xbmc.debug/:/home/thnov/.xbmc/addons/script.module.parsedom/lib:/home/thnov/.xbmc/addons/script.module.xbmcswift2/lib:/home/thnov/.xbmc/addons/script.module.elementtree/lib:/home/thnov/.xbmc/addons/script.module.requests2/lib:/home/thnov/.xbmc/addons/script.module.simple.downloader/lib:/home/thnov/.xbmc/addons/script.module.buggalo/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-i386-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gst-0.10:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client
21:11:35 T:2136447808   DEBUG: CPythonInvoker(85, /home/thnov/.xbmc/addons/plugin.video.svtplay/default.py): entering source directory /home/thnov/.xbmc/addons/plugin.video.svtplay
21:11:35 T:2136447808   DEBUG: CPythonInvoker(85, /home/thnov/.xbmc/addons/plugin.video.svtplay/default.py): instantiating addon using automatically obtained id of "plugin.video.svtplay" dependent on version 2.14.0 of the xbmc.python api
21:11:35 T:2136447808  NOTICE: CommonFunctions-2.5.1
21:11:35 T:2996102976   DEBUG: ------ Window Init (DialogBusy.xml) ------
21:11:36 T:2136447808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/thnov/.xbmc/addons/plugin.video.svtplay/default.py", line 360, in <module>
                                                viewCategories()
                                              File "/home/thnov/.xbmc/addons/plugin.video.svtplay/default.py", line 101, in viewCategories
                                                categories = svt.getCategories()
                                              File "/home/thnov/.xbmc/addons/plugin.video.svtplay/resources/lib/svt.py", line 63, in getCategories
                                                title = common.parseDOM(article, "h2")[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
21:11:36 T:2996102976   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
21:11:36 T:2136447808    INFO: Python script stopped
21:11:36 T:2136447808   DEBUG: Thread LanguageInvoker 2136447808 terminating
21:11:36 T:2094484288   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
21:11:36 T:2996102976   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=categories
21:11:36 T:2996102976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=categories) failed
21:11:36 T:2996102976   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.svtplay/?mode=search)
21:11:36 T:2996102976   DEBUG:   ParentPath = [plugin://plugin.video.svtplay/]
21:11:36 T:2996102976   DEBUG: Loading items: 11, directory: plugin://plugin.video.svtplay/?mode=search sort method: 0, ascending: false
21:11:36 T:2996102976   DEBUG: RunQuery took 2 ms for 224 items query: SELECT  files.strFilename, files.playCount,  bookmark.timeInSeconds, bookmark.totalTimeInSeconds FROM files  LEFT JOIN bookmark ON    files.idFile = bookmark.idFile AND bookmark.type = 1  WHERE files.idPath=2047
21:11:36 T:2136447808  NOTICE: Thread BackgroundLoader start, auto delete: false
21:11:36 T:2136447808   DEBUG: Thread BackgroundLoader 2136447808 terminating
21:11:36 T:2996102976   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
^C

**Comment by kokangit** [comment]
I experience this same problem. In my fork I have made a fix for this. Pick up the file svt.py and install it.
https://github.com/kokangit/xbmc-svtplay

**Comment by linqcan** [comment]
will fix!

**Comment by linqcan** [comment]
Fixed
