### ISSUE TITLE
Favorites doesn't work

### ISSUE THREAD

**Issue by ghost** [kodi-svtplay/xbmc-svtplay#104]
I have tried favorites but it generates an error

This is from xbmc.log:

22:25:00 T:2996102976  NOTICE: Starting XBMC (13.2 Git:0f3db05). Platform: x86 Linux 32-bit

21:18:02 T:2996102976   DEBUG: LIRC: Update - NEW at 151271654:000000037ff07be8 00 KEY_RECORD mceusb (KEY_RECORD)
21:18:02 T:2996102976   DEBUG: OnKey: 232 (0xe8) pressed, action is ContextMenu
21:18:02 T:2996102976   DEBUG: ------ Window Init (DialogContextMenu.xml) ------
21:18:03 T:2996102976   DEBUG: LIRC: Update - NEW at 151273147:000000037ff07bdd 00 KEY_OK mceusb (KEY_OK)
21:18:03 T:2996102976   DEBUG: OnKey: 11 (0x0b) pressed, action is Select
21:18:04 T:2996102976   DEBUG: ------ Window Deinit (DialogContextMenu.xml) ------
21:18:04 T:1348803392  NOTICE: Thread LanguageInvoker start, auto delete: false
21:18:04 T:1348803392    INFO: initializing python engine.
21:18:04 T:1348803392   DEBUG: CPythonInvoker(94, special://home/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py): start processing
21:18:04 T:1348803392  NOTICE: -->Python Interpreter Initialized<--
21:18:04 T:1348803392   DEBUG: CPythonInvoker(94, special://home/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py): the source file to load is "special://home/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py" ("/home/thnov/.xbmc/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py")
21:18:04 T:1348803392   DEBUG: CPythonInvoker(94, special://home/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py): setting the Python path to /home/thnov/.xbmc/addons/plugin.video.svtplay/resources/lib:/home/thnov/.xbmc/addons/script.module.pyamf/lib:/home/thnov/.xbmc/addons/script.module.xbmcswift/lib:/home/thnov/.xbmc/addons/script.module.simplejson/lib:/home/thnov/.xbmc/addons/script.module.beautifulsoup4/lib:/home/thnov/.xbmc/addons/script.module.beautifulsoup/lib:/usr/share/xbmc/addons/script.module.pil/lib:/home/thnov/.xbmc/addons/script.common.plugin.cache/lib:/home/thnov/.xbmc/addons/script.module.requests/lib:/home/thnov/.xbmc/addons/script.module.mechanize/lib:/usr/share/xbmc/addons/xbmc.debug/:/home/thnov/.xbmc/addons/script.module.parsedom/lib:/home/thnov/.xbmc/addons/script.module.xbmcswift2/lib:/home/thnov/.xbmc/addons/script.module.elementtree/lib:/home/thnov/.xbmc/addons/script.module.requests2/lib:/home/thnov/.xbmc/addons/script.module.simple.downloader/lib:/home/thnov/.xbmc/addons/script.module.buggalo/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-i386-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gst-0.10:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client
21:18:04 T:1348803392   DEBUG: CPythonInvoker(94, special://home/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py): entering source directory /home/thnov/.xbmc/addons/plugin.video.svtplay/resources/lib
21:18:04 T:1348803392  NOTICE: CommonFunctions-2.5.1
21:18:04 T:1348803392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: name 'helper' is not defined
                                            Traceback (most recent call last):
                                              File "/home/thnov/.xbmc/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py", line 86, in <module>
                                                helper.infoMsg("FM called as script!")
                                            NameError: name 'helper' is not defined
                                            -->End of Python script error report<--
21:18:04 T:1348803392    INFO: Python script stopped
21:18:04 T:1348803392   DEBUG: Thread LanguageInvoker 1348803392 terminating
21:18:04 T:2996102976   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
21:18:09 T:2996102976   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
^C

**Comment by kokangit** [comment]
I experience this same problem. In my fork I have made a fix for this. Pick up the file FavoritesManager.py and install it.
https://github.com/kokangit/xbmc-svtplay

**Comment by linqcan** [comment]
Missing import. Fixed.
