### ISSUE TITLE
Script error on Downton Abbey - Avsnitt 1

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#107]
Trying to play Downton Abbey - Avsnitt 1 gives script error:
  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 369, in <module>
    startVideo(ARG_URL)
  File "/home/mgu/projekt/xbmc-svtplay/default.py", line 279, in startVideo
    show_obj = helper.resolveShowURL(url)
  File "/home/mgu/projekt/xbmc-svtplay/resources/lib/helper.py", line 322, in resolveShowURL
    extension = getVideoExtension(video_url)
  File "/home/mgu/projekt/xbmc-svtplay/resources/lib/helper.py", line 354, in getVideoExtension
    url = video_url.split("?")[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kokangit** [comment]
I concluded that for this video there is no videoreference for playertype ios. But I don't really understand the implications for that.

**Comment by kokangit** [comment]
Explanation on web site:
http://www.svt.se/tittarservice/hitta-svar/varfor-fungerar-inte-downton-abbey

**Comment by linqcan** [comment]
Still, the error handling should be better. Will fix that.

**Comment by linqcan** [comment]
Downton Abbey is now available on mobile platforms (as XBMC is identifying itself as) again:
http://www.svt.se/tittarservice/hitta-svar/varfor-fungerar-inte-downton-abbey

Will still try and fix the script error.

@ToddeSwe @kokangit

**Comment by kokangit** [comment]
Thanks for the heads up!

**Comment by ToddeSwe** [comment]
Hi

I can watch it now on both my XBMC/Kodi PC and The Little Black Box. :) THANKS!
