### ISSUE TITLE
Error: ValueError: invalid literal for int():

### ISSUE THREAD

**Issue by gostaj** [kodi-svtplay/xbmc-svtplay#11]
Running:
Python 2.6.6 (r266:84292, Sep 15 2010, 15:52:39) 
[GCC 4.4.5] on linux2 (Ubuntu Linux 2.6.35-27-generic)
Version 10.00~svn35648-maverick1 of xbmc
Version 1.0.3 of the SVT Plugin

21:15:26 T:2847906672 M:1836822528   ERROR: Error Type: exceptions.ValueError
21:15:26 T:2847906672 M:1836822528   ERROR: Error Contents: invalid literal for int():
21:15:26 T:2847906672 M:1836822528   ERROR: Traceback (most recent call last):
                                              File "/home/nugator/.xbmc/addons/plugin.video.svtplay/default.py", line 15, in ?
                                                SETTINGS_HIGHEST_BITRATE = [320, 850, 1400, 2400][int(**settings**.getSetting("highest_bitrate"))]
                                            ValueError: invalid literal for int():
21:15:26 T:3077613440 M:1836822528   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/
21:15:26 T:3077613440 M:1836822528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/) failed

**Comment by nilzen** [comment]
Can you please add the line below on line 14 in the file /home/nugator/.xbmc/addons/plugin.video.svtplay/default.py

xbmc.log("Highest bitrate value: " + **settings**.getSetting("highest_bitrate"))

And post the output of xbmc.log here. It should be something like:
21:37:52 T:2959921152 M:960147456  NOTICE: Highest bitrate value: 3

**Comment by gostaj** [comment]
Seems like the setting is an empty string. Where/when/how are these settings stored/changed?

21:49:00 T:2844818288 M:1415700480  NOTICE: Highest bitrate value:
21:49:00 T:2844818288 M:1415700480   ERROR: Error Type: exceptions.ValueError
21:49:00 T:2844818288 M:1415700480   ERROR: Error Contents: invalid literal for int():
21:49:00 T:2844818288 M:1415700480   ERROR: Traceback (most recent call last):
                                              File "/home/nugator/.xbmc/addons/plugin.video.svtplay/default.py", line 16, in ?
                                                SETTINGS_HIGHEST_BITRATE = [320, 850, 1400, 2400][int(**settings**.getSetting("highest_bitrate"))]
                                            ValueError: invalid literal for int():
21:49:00 T:3054638976 M:1415700480   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/
21:49:00 T:3054638976 M:1415700480   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/) failed

**Comment by nilzen** [comment]
You can change them under addon settings, i will add a coalesce for it in the next update... Try to change the values and see if it works for you then...

**Comment by gostaj** [comment]
Hmm, I can't change the settings either:
- When selecting "Add-on settings" on the plugin I get the message "This Add-on can not be configured".
- The "Configure" menu on the plugin info page is grayed out.

Am I doing something wrong?

**Comment by nilzen** [comment]
No clue why that isn't working for you, try reinstalling the addon.

**Comment by gostaj** [comment]
Didn't have to reinstall it, suddenly it works even though I haven't changed anything. XBMC bug perhaps.
Thanks for your help.
