### ISSUE TITLE
Script fails when trying to watch anything

### ISSUE THREAD

**Issue by hovren** [kodi-svtplay/xbmc-svtplay#112]
Since yesterday (Oct 29) I can not watch any show using this plugin (version 4.0.8 on OpenElec)

Steps to reproduce:
Try to watch any program, or the live channel feeds.

Apparently there was an [update to SVT Play](http://www.svt.se/tittarservice/fraga-oss/dialog/517563) yesterday which I guess caused this.

**Comment by allwi290** [comment]
19:15:53 T:140149958608640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "~/.xbmc/addons/plugin.video.svtplay/default.py", line 360, in <module>
                                                viewCategories()
                                              File "~/.xbmc/addons/plugin.video.svtplay/default.py", line 101, in viewCategories
                                                categories = svt.getCategories()
                                              File "~/.xbmc/addons/plugin.video.svtplay/resources/lib/svt.py", line 70, in getCategories
                                                category["thumbnail"] = BASE_URL + thumbs[index]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
19:15:53 T:140151228168128   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=categories
19:15:53 T:140151228168128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=categories) failed

**Comment by perheld** [comment]
Same here. Log:

21:32:36 T:2730488912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/default.py", line 379, in <module>
                                                viewChannels()
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/default.py", line 149, in viewChannels
                                                channels = svt.getChannels()
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/resources/lib/svt.py", line 239, in getChannels
                                                title = common.parseDOM(box, "a", attrs = {"class" : anchor_class}, ret = "title")[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
21:32:36 T:3059511296   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=kanaler
21:32:36 T:3059511296   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=kanaler) failed

**Comment by gonzzor** [comment]
Check this pull request, it should deal with the site changes.

https://github.com/nilzen/xbmc-svtplay/pull/111

**Comment by pacmyc** [comment]
I had the same problem but gonzzor's solution worked, thanx!

**Comment by linqcan** [comment]
merged
