### ISSUE TITLE
Channels not populated

### ISSUE THREAD

**Issue by timgiles** [kodi-svtplay/xbmc-svtplay#118]
On a new install of Kodi, the Channels folder is not being populated. I believe the issue cropped up in the last couple of days. Running the unit tests I get the following (I have just cut out the relevent sections for brevity):

.[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/kanaler'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: No container found for channels'
# 
## FAIL: test_alphabetic (testSvt.TestSvtModule)

Traceback (most recent call last):
  File "testSvt.py", line 27, in test_alphabetic
    self.assertHasContent(programs)
  File "testSvt.py", line 22, in assertHasContent
    self.fail("List is empty")
AssertionError: List is empty
# 
## FAIL: test_get_channels (testSvt.TestSvtModule)

Traceback (most recent call last):
  File "testSvt.py", line 108, in test_get_channels
    self.assertHasContent(items)
  File "testSvt.py", line 19, in assertHasContent
    self.fail("List is None")
AssertionError: List is None

**Comment by linqcan** [comment]
Fixed
