### ISSUE TITLE
Abrupt ending after a few seconds, swf verify

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#12]
Some programs use swf verify and since this is not enabled for svtplay plugin, the player ends after a few seconds.
In the log you can see this:
18:56:52 T:2863111024 M:2030936064    INFO: HandleCtrl, SWFVerification ping received:
18:56:52 T:2863111024 M:2030936064   ERROR: HandleCtrl: Ignoring SWFVerification request, use --swfVfy!

Here is a user with problem writing in the forum:
http://forum.xbmc.org/showpost.php?p=978729&postcount=115

The solution is to tell xbmc-player to use swf verification. This can be done in the URL for the program like this:
url = params["url"] + " swfUrl=http://svtplay.se/flash/svtplayer-2011.18.swf swfVfy=1"

I have tried this and it seems to work well.

Two problems:
1) I can not understand how to tell which programs that need swf verify. But enabling it for all programs may not be a problem. I have not seen any problems so far enabling for all programs.
2) The URL to svt flash player is hard coded and the URL may be changed by svt. If you browse svtplay.se with a browser and look at the html-code you can find:
<param name="movie" value="/flash/svtplayer-2011.18.swf" />
But I cannot find the URL in the xml. I have no idea how to solv this. Any ideas anyone?

**Comment by nilzen** [comment]
If I remember it correctly, it's not allowed to use swfverify in addons that are in the official xbmc repo.

**Comment by kokangit** [comment]
I have no idea about that. But grep in my plugin directory reveals that YouTubePlayer and xot uses swfvfy,

**Comment by nilzen** [comment]
Xot isn't in the official repo and i'm not sure if YouTubePlayer is the youtube addon in the official repo, is it?

**Comment by kokangit** [comment]
You are correct about xot, it is not official. But I have made my best to verify YouTube, it is the actual official plugin that uses swfvfy. I'm sure.
I have also tried to find info about the rules for the official plugins. I still have not seen anything about swfvfy.

**Comment by kokangit** [comment]
I am not saying you are wrong or this proves anything but I think it may indicate that this is indeed allowed.
I downloaded all video plugins from git://xbmc.git.sourceforge.net/gitroot/xbmc/plugins and did a grep for swfurl. The following official video plugins seems to use swfvfy:

 ./plugin.video.mediathek/mediathek/arte.py
./plugin.video.nz.ondemand/tv3.py
./plugin.video.nz.ondemand/tvnz.py
./plugin.video.mlbmc/default.py
./plugin.video.hgtv/default.py
./plugin.video.diy/default.py
./plugin.video.pelisalacarta/lib/gdata/youtube/**init**.py
./plugin.video.pelisalacarta/core/trailertools.py
./plugin.video.pelisalacarta/servers/youtube.py
./plugin.video.pelisalacarta/servers/yahoo.py
./plugin.video.pelisalacarta/servers/megalive.py
./plugin.video.youtube/YouTubePlayer.py
./plugin.video.twit/default.py
./plugin.video.yousee.tv/addon.py
./plugin.video.tvalacarta/youtubeAPI/gdata/youtube/**init**.py
./plugin.video.tvalacarta/channels/tva.py
./plugin.video.tvalacarta/servers/trailertools.py
./plugin.video.vimeo/VimeoNavigation.py
./plugin.video.foodnetwork/default.py
./plugin.video.joeroganexperience/ustream.py

**Comment by nilzen** [comment]
Interesting... I will go on IRC and see if I can get a clearer answer there.

**Comment by nilzen** [comment]
This is the best info i've found so far http://forum.xbmc.org/showthread.php?p=590370#post590370

**Comment by kokangit** [comment]
Searching that thread for "rtmpe" gets me here:
http://forum.xbmc.org/showthread.php?p=614248&highlight=rtmpe#post614248

It looks like "they" have lightened up a bit.
:)

**Comment by nilzen** [comment]
Wow, thats great news! I think we'll have to hard code the swf url and bump the version if the location changes... Do you have the code ready or do you want me to implement it? Regarding which videos needs it or not, i think it's ok to use it on all videos...

**Comment by kokangit** [comment]
diff --git a/default.py b/default.py
index 3180f5f..5cb2f3c 100644
--- a/default.py
+++ b/default.py
@@ -307,6 +307,8 @@ def add_directory_item(name, params={}, thumbnail=None, isFolder=True,
                url = sys.argv[0] + '?' + urllib.urlencode(params)
        else:
                url = params["url"]
-               if url.find('rtmp') == 0:
-                       url += " swfUrl=http://svtplay.se/flash/svtplayer-2011.18.swf swfVfy=1"
              if not infoLabels:
                      infoLabels = { "Title": name }
              li.setInfo(type="Video", infoLabels=infoLabels)

It will probably be fixed faster if you do the simple change. Just added 2 lines of code. I saw that xot checked for rtmp so I did the same as you can see.

I've seen other plugins hardcoding this also.

**Comment by nilzen** [comment]
I finally found a few minutes to add this and fixed another issue i found with title encodings. Can you pull the latest version from github, the master branch, and test it before i ask for a pull to the addon repo. I will ask the same in the forum thread later tonight after i tested it my self a bit more.
