### ISSUE TITLE
"Dependencies not met"  

### ISSUE THREAD

**Issue by liftarn** [kodi-svtplay/xbmc-svtplay#120]
When trying to update I get the message "Dependencies not met". What has changed?

**Comment by linqcan** [comment]
Just updated a windows box with gotham and did not see this.
Please supply the following information:
- Platform (windows/linux...)
- XBMC version
- SVT Play
- XBMC log file (if possible)

**Comment by liftarn** [comment]
I'm running on a Raspberry Pi with Raspbmc. Haven't figured out how to get the XBMC version, but I have auto update set.

**Comment by linqcan** [comment]
Version: http://kodi.wiki/view/Android_FAQ#How_do_I_find_out_what_version_of_XBMC_am_I_running.3F

Try reinstalling the addon if you still have issues. No new dependencies have been added to the addon.
