### ISSUE TITLE
Categories empty

### ISSUE THREAD

**Issue by alsdfjldafsjalsfjk** [kodi-svtplay/xbmc-svtplay#122]
Recently the categories in the add-on started showing empty. Only one category works and it's "popular".

**Comment by linqcan** [comment]
Some major site changes. Will attend this during the weekend as SVT pushes changes on fridays as well.

**Comment by linqcan** [comment]
Update 4.0.14 is on its way out. Please create a new issue ticket if the issue still exists on 4.0.14.

**Comment by alsdfjldafsjalsfjk** [comment]
Thank you!
