### ISSUE TITLE
Compatibility with PlayToKodi chrome extension 

### ISSUE THREAD

**Issue by Deph0** [kodi-svtplay/xbmc-svtplay#128]
Using PlayToKodi is amazing, it supports a great amount of websites (not all listed however, so you kinda have to try-and-error, or look into the code), I was thinking if it's possible to use the plugin:// uri scheme to launch svtplay and direct it to the video.

for example, as done for twitch:

``` javascript
callback('plugin://plugin.video.twitch/playLive/' + videoId + '/');
```

> > https://github.com/khloke/play-to-xbmc-chrome/blob/master/js/modules.js#L333

**Comment by linqcan** [comment]
Sorry for the late reply!
This is the URL scheme to start this [1] SVT video:

```
plugin://plugin.video.svtplay/?url=%2Fvideo%2F2905187%2Fdelat-land-med-niklas-kallner%2Fdelat-land-med-niklas-kallner-avsnitt-4&mode=video
```

[1] http://www.svtplay.se/video/2905187/delat-land-med-niklas-kallner/delat-land-med-niklas-kallner-avsnitt-4

Happy hacking!

**Comment by Deph0** [comment]
Thanks! 
Can you also tell me how i can implement this for oppetarkiv?
And perhaps for SVTPlays time-jump feature (found in 'dela' menu) (e.g. [1])?

[1] http://www.svtplay.se/video/2905187/delat-land-med-niklas-kallner/delat-land-med-niklas-kallner-avsnitt-4?position=600

**Comment by Deph0** [comment]
Made a pull request, without oppetarkiv/timejump feature! woo!

> > https://github.com/khloke/play-to-xbmc-chrome/pull/51

**Comment by linqcan** [comment]
Ah, nice! :+1:
