### ISSUE TITLE
Thumbnails not working

### ISSUE THREAD

**Issue by matling** [kodi-svtplay/xbmc-svtplay#129]
Since a few weeks thumbnails for shows and episodes are not working.

**Comment by linqcan** [comment]
Thank you for reporting this issue!
I will try and resolve this asap.

**Comment by matling** [comment]
This fixes the broken links. However, the prepareThumb function is not used in all thumbnail cases, for instance in Categories -> Category -> Programs. I have submitted pull request #133 that fixes this.
