### ISSUE TITLE
Swedish characters doesn't work

### ISSUE THREAD

**Issue by nybogard** [kodi-svtplay/xbmc-svtplay#131]
When viewing info about current broadcasts, all Swedish characters that are fetched from SVT's website is outputted in html-code format, i.e. `sändningsuppehåll` is displayed as `s&auml;ndningsuppeh&aring;ll`. I've tried using Kodi with both English and Swedish as language.  
- xbmc-svtplay v4.0.15
- Kodi v14.2
- OpenELEC v5.0.8
- Raspberry Pi 2 Model B

![screenshot](https://cloud.githubusercontent.com/assets/5082913/7549301/db9029f4-f62f-11e4-9f59-4df8a348232a.png)

**Comment by linqcan** [comment]
Thank you for reporting this issue!
In the future, please submit a Pull Request (PR) with your fix and I can one-click merge it :+1:

**Comment by linqcan** [comment]
nevermind, I am blind...
There is already a PR :+1:

**Comment by nybogard** [comment]
I'm kinda new to GitHub and pull requests, but aren't I supposed to get some notification when there's been a merge?

**Comment by linqcan** [comment]
see PR comment. there was no merge since I suffered from temporary blindness and missed your PR...

**Comment by nybogard** [comment]
Ah, got it.
