### ISSUE TITLE
Addon buffers a lot

### ISSUE THREAD

**Issue by ghallberg** [kodi-svtplay/xbmc-svtplay#134]
In the last few weeks SVTPlay has started buffering unreasonably often.

No other video addons are affected (twitch, youtube etc), also watching through the SVTPlay homepage also works fine on the same network etc.

Looking at the debug display, the cache starts emptying and doesn't refill before hitting 0. On twitch there are intermittent cache drops, but it fills up before hitting 0 and buffering.

**Comment by linqcan** [comment]
Unfortunately this can't be addon related. It would be either XBMC/kodi that has changed behavior or SVT's streaming servers. As the addon is only parsing URLs and feeding them to the XBMC/kodi player.

If you haven't done any XBMC/kodi upgrades in between the tries, then it is most likely SVT's servers that are not providing the streams as they used to.

Note that the SVTPlay website and the addon uses different ways of streaming (assuming the normal flash player is used).

**Comment by ghallberg** [comment]
It's sad that this makes the addon completely useless to me. It buffers every few minutes, and each time it skips ahead so that the viewing becomes not just stuttering, but also incomplete.

I've tested the retrospective addon as well, which seems to have the same issue, so you are most probably correct about this being Kodi/SVTs issue. I wish there was a solutino for it.

**Comment by nybogard** [comment]
I haven't noticed any of the problems you describe. I run OpenELEC 5.0.8 on Raspberry Pi 2 with version 4.0.17 of the add-on.

**Comment by ghallberg** [comment]
That's interesting. Thank you for the input. I'll have to think further about what might be causing the issue.
