### ISSUE TITLE
Possible to rewind live broadcasts from the start

### ISSUE THREAD

**Issue by rikardfalkeborn** [kodi-svtplay/xbmc-svtplay#135]
When starting to stream a program that is currently live broadcast, the stream starts from where the current broadcast is. That is all good, but sometimes, I want to see the program from the start (this is typically the case when I watch the news, or the Sportnytt, where it can be very annoying when I have to wait for ten minutes to see the news from the start).

So, ideally, the addon would work like when watching in a browser, clicking on a live broadcast starts from the "live" time, but with a possibility to rewind it from the start. I don't know if that is possible to do, but it would be awesome if it was.

Thanks for a great addon.

**Comment by linqcan** [comment]
Hi,

I think this is a limitation in the XBMC player the addon is using. I don't think there is anything the addon can change to satisfy your request. You should instead look into how the XBMC player works.
Will close but we can still continue to discuss here if you'd like.

https://github.com/xbmc/xbmc
