### ISSUE TITLE
Barnkanalen and SVT24 broken

### ISSUE THREAD

**Issue by ghallberg** [kodi-svtplay/xbmc-svtplay#136]
The other Channels work, but something changed here apparently :(

**Comment by ghallberg** [comment]
It seems to only be an issue with hls streams.

**Comment by linqcan** [comment]
Sorry for the delay in answering. Is this still an issue?

//Erik

**Comment by ghallberg** [comment]
Seems to have solved itself. For the record I could work around it by using the "don't use <whatever file format> stream" option. Now it's back to working as normal again though.

**Comment by linqcan** [comment]
Strange, good thing it is working again!
