### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by datamaskinen** [kodi-svtplay/xbmc-svtplay#143]
My sound works perfect in 5 sec den no sound.
Is this some buffer problem or is it someone els having the same problem ?

Kodi 15.2
svtplay 4.9.18

**Comment by jhagberg** [comment]
Just switch to a new machine and kodi 16.0 I got sort of the same issue. 
Fist it play all well then the sound do not work any longer and the video is "laggy"

**Comment by linqcan** [comment]
This is a Kodi issue, the plug-in doesn't do anything with the streams
except giving them to Kodi. I suggest you try the Kodi forums.
