### ISSUE TITLE
Broken after svtplay redesign

### ISSUE THREAD

**Issue by wader** [kodi-svtplay/xbmc-svtplay#144]
Hi! seems like the plugin is quite broken after redesign today
http://svti.svt.se/2015/12/svt-plays-nya-skyltfonster/

I might spend some time trying to figure how to make it work again. Will post progress it so.

**Comment by linqcan** [comment]
Will look into this. Read on their blog about them transitioning to a new
framework in several steps. So a complete rewrite of this plugin should
probably wait until their new app is live for real. Until then some
patching to the scraper will do.

**Comment by wader** [comment]
:+1: let me know if you want help! i use the plugin a lot :smile:

**Comment by linqcan** [comment]
I have studied the new structure now and I think I know how to change the plugin for it to work. However, it will take a couple of days (evening/nights) more until I can have it working.

In short, the scraper will not scrape the main page anymore as the DOM is hard to navigate now (missing identifiers on divs etc) but instead scrape every section's subpage. Will use the "raw data" from the ajax calls they are doing.

Phase 1, and first release, will be to have the sections on the main page working. After that I will try and get program pages etc working. That should give most people something usable until we are feature complete again.

If you have any proposals for how to change/solve this you can share them here or via a pull request :smile:

**Comment by wader** [comment]
No worries! Ill let you know if i digg into something and im up for testing stuff if you want

**Comment by linqcan** [comment]
Please test this one!
See release notes for installation instructions.

https://github.com/nilzen/xbmc-svtplay/releases/tag/v4.0.20-beta

My kodi installation (ubuntu 14.04.03) had issues with playing video (sound but black screen), let me know if you are seeing them too.

**Comment by wader** [comment]
Works great, no problem with sound or video. Testing with kodi 16.0-ALPHA1 on a Firetv. Looked at the commits and the changes looked surprisingly small :smile: 

Stort tack!

**Comment by linqcan** [comment]
Great!

Will try and push this to kodi during the day. When it is live you need to
uninstall the beta and re-download the plug in through kodi. Will post here
when it is live.

**Comment by khoda** [comment]
Awesome work @linqcan . Looks good and works fine on Ubuntu 14.04.3 LTS, Kodi 16 beta 3 (2:16.0~git20151206.1622-beta3-0trusty).

Only thing I noticed is the handling of special characters. åäö is shown as HTML symbols(&auml ;). 
Happens to episodes titles under "Program A-Ö" after a show has been selected. 

See PR https://github.com/nilzen/xbmc-svtplay/pull/145

Edit: PR

**Comment by rysport** [comment]
Works fine on Rpi2 Openelec 16. Is there a reason why latest news was removed?

**Comment by linqcan** [comment]
@khoda Saw the PR, Thanks! I haven't been able to get XBMC to pull my latest update yet, vacation mode suspected.

@rysport Was not working as wanted and I prioritized to get the other stuff out fast. Will try and get it back during Christmas.

**Comment by linqcan** [comment]
Fyi: update request was sent to xbmc/kodi on December 20 but they haven't acted on it yet:
http://sourceforge.net/p/xbmc/mailman/message/34709969/

**Comment by linqcan** [comment]
v4.0.20 is now live. Please uninstall the beta if you have installed it previously and install from the official repository.

God jul!
