### ISSUE TITLE
Latest News is missing

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#146]
@rysport 

Fixed in 875e2eb0dacda04073d86d27b414a357baf766dc

**Comment by rysport** [comment]
Thanks!
Den 7 jan 2016 21:37 skrev "Erik Lindqvist" notifications@github.com:

**Comment by linqcan** [comment]
Requested pull from kodi. Still waiting for them to acknowledge and pull.

**Comment by linqcan** [comment]
Should be live now.
