### ISSUE TITLE
Live boardcasts not working - Windows

### ISSUE THREAD

**Issue by tactmaster** [kodi-svtplay/xbmc-svtplay#156]
In Kodi when I try and run live boardcast it, says error and tells me too look at the error logs. 
I am using the lastest version

attached is the log

[kodierror.log.txt](https://github.com/nilzen/xbmc-svtplay/files/211870/kodierror.log.txt)

Thanks

**Comment by linqcan** [comment]
Please provide the steps you take in order to produce this fault.

**Comment by castalla** [comment]
Same problem on Kodi arm SVTplay 4.0.25

Selecting a live channel produces a script error

**Comment by tactmaster** [comment]
Channels -> SVT1 (or any of the channels)

**Comment by linqcan** [comment]
Can't play the streams using a local player either. Could be issues with the streams?
Anyone with an iOS device that can confirm that "Kanaler" works there?

**Comment by linqcan** [comment]
Found a glitch in the plugin too. Working on a fix.
