### ISSUE TITLE
Can't fetch episodes anymore

### ISSUE THREAD

**Issue by jensbengtsson** [kodi-svtplay/xbmc-svtplay#158]
Since about two days ago this addon doesn't fetch/list any episodes for me anymore when I use the programs listing and choose a show.

**Comment by linqcan** [comment]
What version are you running?
Will look into this.

Thanks for reporting!

**Comment by jensbengtsson** [comment]
4.0.26 on openelec 6.0.3

**Comment by kimlid** [comment]
I have the same problem, same version, same OS as jensbengtson (above)

**Comment by linqcan** [comment]
Yep. It's broken. The fix will be up soon.

**Comment by linqcan** [comment]
Should be fixed in next version. I have requested a pull
https://github.com/xbmc/repo-plugins/pull/447
