### ISSUE TITLE
all programs seems to be brokem at this moment

### ISSUE THREAD

**Issue by sopparus** [kodi-svtplay/xbmc-svtplay#159]
13:03:42 705279.750000 T:1962058416   ERROR: Playlist Player: skipping unplayabl                                                                                      e item: 0, path [plugin://plugin.video.svtplay/?url=%2Fvideo%2F9204633%2Fnormalt                                                                                      -liv%2Fnormalt-liv-avsnitt-1&mode=video]
13:03:42 705279.750000 T:1962058416   DEBUG: Playlist Player: one or more items                                                                                       failed to play... aborting playback

tried windows kodi and libreelec (16.1)
also retrospect is broken but it works through chrome so something must have changed

**Comment by linqcan** [comment]
Thanks for reporting!
There seems to have been a major site change. Will look into this.

**Comment by linqcan** [comment]
Most issues should be fixed now. I have requested an update: https://github.com/xbmc/repo-plugins/pull/553
