### ISSUE TITLE
Livesändningar funkar inte.

### ISSUE THREAD

**Issue by nanab** [kodi-svtplay/xbmc-svtplay#16]
När man försöker kolla på livesändningar så stänger den ner efter ett par sekunder.
Felet verkar vara att den inte hittar swf playern. Jag ändrade raden SWF_PLAYER_URL i default..py till
SWF_PLAYER_URL = "http://www.svtplay.se/public/swf/video/svtplayer-2012.28.swf"

Sen fungerar Livesändningar ok.

**Comment by nilzen** [comment]
Vilken xbmc-version kör du med? Har testat med den senaste nightly samt med 11.0 och den spelar bara 4 sekunder för mig innan strömmen stoppas igen med uppdaterad SWF_PLAYER_URL

**Comment by craziemac** [comment]
Har också detta problemet. Kör raspbmc med xbmc 12 alpha2. Svt play addon 2.0.3.

Edit: ändringen av SWF_PLAYER_URL fixade det.

**Comment by nanab** [comment]
Jag kör på 11.0 ifrån http://packages.pulse-eight.net/. Har provat på en dator med ubuntu 12.04 och på en med xbmcbuntu. Svt player är tagen härifrån idag. v2.0.3

**Comment by hmps** [comment]
Jag kan också bekräfta fixen med SWF_PLAYER_URL="http://www.svtplay.se/public/swf/video/svtplayer-2012.28.swf" 

11.0, SVT Player 2.0.3

**Comment by nilzen** [comment]
Fixat nu, uppdateras förhoppningsvis snart i det officiella repot. Se https://github.com/nilzen/xbmc-svtplay/pull/17
