### ISSUE TITLE
many things seem broken again

### ISSUE THREAD

**Issue by abjorck** [kodi-svtplay/xbmc-svtplay#161]
i guess they're still changing things?

**Comment by linqcan** [comment]
Could you please state what is not working and what kind of error messages
you are getting in the logs? Thanks!

**Comment by abjorck** [comment]
categories and programs cause just an error popup

from log:
20:13:52 96936.757812 T:1582298176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('thumbnailMedium',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 362, in <module>
                                                viewEpisodes(ARG_URL)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 165, in viewEpisodes
                                                episodes = svt.getEpisodes(url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svt.py", line 307, in getEpisodes
                                                program["thumbnail"] = helper.prepareThumb(item["thumbnailMedium"], BASE_URL)
                                            KeyError: ('thumbnailMedium',)
                                            -->End of Python script error report<--
20:13:53 96936.945312 T:1968078848   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=pr&url=%2fmorph
20:13:53 96936.945312 T:1968078848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=pr&url=%2fmorph) failed
20:13:53 96937.390625 T:1582298176  NOTICE: Thread BackgroundLoader start, auto delete: false
20:14:10 96954.210938 T:1582298176  NOTICE: Previous line repeats 1 times.
20:14:10 96954.210938 T:1582298176  NOTICE: Thread LanguageInvoker start, auto delete: false
20:14:10 96954.351562 T:1582298176  NOTICE: -->Python Interpreter Initialized<--
20:14:11 96954.820312 T:1582298176  NOTICE: CommonFunctions-2.5.1
20:14:12 96956.265625 T:1548743744  NOTICE: Thread BackgroundLoader start, auto delete: false
20:14:18 96962.187500 T:1582298176  NOTICE: Thread LanguageInvoker start, auto delete: false
20:14:18 96962.320312 T:1582298176  NOTICE: -->Python Interpreter Initialized<--
20:14:18 96962.765625 T:1582298176  NOTICE: CommonFunctions-2.5.1
20:14:20 96964.179688 T:1582298176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('thumbnailLarge',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 360, in <module>
                                                viewCategory(ARG_URL)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 155, in viewCategory
                                                programs = svt.getProgramsForCategory(url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svt.py", line 123, in getProgramsForCategory
                                                return getProgramsForGenre(url.split("/")[1])
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svt.py", line 144, in getProgramsForGenre
                                                program = { "title": title, "url": url, "thumbnail": helper.prepareThumb(item["thumbnailLarge"], baseUrl=BASE_URL), "info": info}
                                            KeyError: ('thumbnailLarge',)
                                            -->End of Python script error report<--
20:14:20 96964.359375 T:1968078848   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=ti&url=genre%2fdokumentar
20:14:20 96964.367188 T:1968078848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=ti&url=genre%2fdokumentar) failed

can i get more detail in the log or is this helpful?

**Comment by linqcan** [comment]
Yep, that's helpful. Thanks!

Missing a fallback I see. Will fix.

**Comment by linqcan** [comment]
Fixed and requested an update pf plugin: https://github.com/xbmc/repo-plugins/pull/558
