### ISSUE TITLE
Error check log for details

### ISSUE THREAD

**Issue by ptryk** [kodi-svtplay/xbmc-svtplay#162]
Hi from about 2 days ago without making any known changes the addon has stopped working. when in either osmc or openelec on both a rpi 2b+ and a pi0 when going into a menu choice such as "programs a-ö" it says
Svt play error please check log file for more info

I find nothing for svt in the kodi log file.

**Comment by linqcan** [comment]
Yes it's broken. See #161. A fix has been submitted but Kodi has not
deployed it yet.
