### ISSUE TITLE
Latest news don't work

### ISSUE THREAD

**Issue by ToddeSwe** [kodi-svtplay/xbmc-svtplay#165]
When trying to see the latest news it fails.

**Comment by linqcan** [comment]
Noted! Working on it.

**Comment by ToddeSwe** [comment]
Hope I didn't do anything wrong pointing this out here?! And thanks for making this addon.

**Comment by linqcan** [comment]
Nope, all good 😀
Thanks for reporting the issue!

**Comment by linqcan** [comment]
@ToddeSwe What is it that it not working for you?
Please state steps needed to reproduce your issue.

I had issues with one specific video file, but it solved itself (SVT issue). Now everything seems to be working without me doing any changes.

**Comment by ToddeSwe** [comment]
Hi
When i try to see the latest available news or the next latest one. Will try before i post this reply!
Nope non of them is working. Here's a errorfile: http://pastebin.com/jvGP5Nv3 It seems like everything besides the news is working.

**Comment by linqcan** [comment]
Judging by the log it looks Kodi related:
`16:58:32 T:7472   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer`

Can you play any other shows using the plugin?

I can't reproduce it on my box (Ubuntu 14.04, Kodi 16.1).

**Comment by ToddeSwe** [comment]
Yes most of it works. And the only part I use is the news. He he have tried both on my pic install and my libreelec install but it's the same.

**Comment by linqcan** [comment]
I can reproduce it now. Seems like enabling "Don't use avc1.77..." in the SVT Play settings works as a workaround.
I will look into the real issue now :smile:

**Comment by ToddeSwe** [comment]
Tried but I can't play any news even when turning this off.

**Comment by ToddeSwe** [comment]
Sorry! Forgotten to press the ok button in settings to save. 😩

**Comment by linqcan** [comment]
Fixed it.
Submitted my change to Kodi and its awaiting their approval.
https://github.com/xbmc/repo-plugins/pull/683

**Comment by ToddeSwe** [comment]
There should be a shrine for you for us to worship. 😜 Thanks.

**Comment by abjorck** [comment]
saw this issue on a couple different programs today, nice to see you're on top of it! 👍

**Comment by linqcan** [comment]
Fix should be live now. If you have version "dot 32" and still have issues;
Please file a new issue ticket with a log.
