### ISSUE TITLE
No news what so ever in latest news

### ISSUE THREAD

**Issue by ToddeSwe** [kodi-svtplay/xbmc-svtplay#167]
Once again they have messed it up and now i can't see any programs at all in latest news category.

**Comment by linqcan** [comment]
Top level menu item "Latest news broadcast" is confirmed broken.
You can still watch news via "Categories->Nyheter".

Working on a fix, no ETA.

**Comment by linqcan** [comment]
Fixed in 116f521047918d2851c5366e2568b76ed21773f6

Requested update from Kodi: https://github.com/xbmc/repo-plugins/pull/702
