### ISSUE TITLE
News section broken and more.

### ISSUE THREAD

**Issue by ToddeSwe** [kodi-svtplay/xbmc-svtplay#168]
Hi
News section is broken, and many more sections as well. Major update at SVT maybe. :(

**Comment by ToddeSwe** [comment]
Logfile: http://pastebin.com/Q2C3vXnw

**Comment by linqcan** [comment]
Confirmed, much of the backend has changed. Will investigate.

**Comment by ToddeSwe** [comment]
How can i see when this is fixed? Will i be notified in some way? Don't remeber how it went last time. :)

**Comment by linqcan** [comment]
- I usually comment when I am done and have submitted the update to Kodi
- You will receive an update notification in Kodi
- Hopefully you will notice that things are working again

As of now I am still working on this. No ETA unfortunately.

**Comment by ToddeSwe** [comment]
Ok thanks for telling me. 😃

Get Outlook for iOS

On Wed, Nov 16, 2016 at 9:39 PM +0100, "Erik Lindqvist" notifications@github.com wrote:
- I usually comment when I am done and have submitted the update to Kodi
- You will receive an update notification in Kodi
- Hopefully you will notice that things are working again

As of now I am still working on this. No ETA unfortunately.

**Comment by linqcan** [comment]
Version 4.0.35 has been submitted to Kodi and they will push it when they are ready.
https://github.com/xbmc/repo-plugins/pull/763
