### ISSUE TITLE
News section is not working

### ISSUE THREAD

**Issue by ToddeSwe** [kodi-svtplay/xbmc-svtplay#173]
The news section is not working. Tried every other ones but they seems to work.

**Comment by linqcan** [comment]
Please specify what mean by steps to reproduce.
Both "Latest news broadcasts" and "Category"->"Nyheter" works here.

**Comment by ToddeSwe** [comment]
Strange, the latest news section doesn't work here. Tonight and a couple of days I'll be moving so. Maybe I can make a log file tonight before...

Get Outlook for iOS




On Wed, Nov 30, 2016 at 10:43 PM +0100, "Erik Lindqvist" <notifications@github.com> wrote:












Please specify what mean by steps to reproduce.

Both "Latest news broadcasts" and "Category"->"Nyheter" works here.

**Comment by linqcan** [comment]
I'm sorry but I still do not know what you refer to when you say "latest
news section". Please state the steps required to reproduce this problem.

**Comment by ToddeSwe** [comment]
In Swedish it says senaste nyheterna and when trying to use it it fails. 

Get Outlook for iOS




On Thu, Dec 1, 2016 at 7:31 AM +0100, "Erik Lindqvist" <notifications@github.com> wrote:










I'm sorry but I still do not know what you refer to when you say "latest

news section". Please state the steps required to reproduce this problem.

**Comment by ToddeSwe** [comment]
Here is a log file: http://pastebin.com/XjTxPMca

**Comment by linqcan** [comment]
Got it now as well. Seems like the data from SVT varies. Will push a fix.

**Comment by linqcan** [comment]
They changed the API just when I was doing this fix. Lots of other stuff are broken now including news. Will open new ticket for it.

**Comment by ToddeSwe** [comment]
How come they're changing all the time?

Get Outlook for iOS




On Fri, Dec 2, 2016 at 7:04 PM +0100, "Erik Lindqvist" <notifications@github.com> wrote:












They changed the API just when I was doing this fix. Lots of other stuff are broken now including news. Will open new ticket for it.

**Comment by linqcan** [comment]
They are changing/improving/developing their service I suppose? :smile:

**Comment by ToddeSwe** [comment]
But every other week 😃 as long as you're not complaining. I'm so greatful for you making this addon. Thanks for keeping it alive. 

Get Outlook for iOS




On Fri, Dec 2, 2016 at 7:07 PM +0100, "Erik Lindqvist" <notifications@github.com> wrote:












They are changing/improving/developing their service I suppose? 😄
