### ISSUE TITLE
ImportError: cannot import name OrderedDict

### ISSUE THREAD

**Issue by jimbju** [kodi-svtplay/xbmc-svtplay#175]
Since a few days back I'm getting the following error.

macOS Sierra
Kodi (16.1 Git:2016-04-24-c327c53)
svtplay 4.0.37

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name OrderedDict
                                            Traceback (most recent call last):
                                              File "/Users/jim/Library/Application Support/Kodi/addons/plugin.video.svtplay/default.py", line 16, in <module>
                                                import resources.lib.FavoritesManager as FavoritesManager
                                              File "/Users/jim/Library/Application Support/Kodi/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py", line 4, in <module>
                                                from collections import OrderedDict
                                            ImportError: cannot import name OrderedDict
                                            -->End of Python script error report<--
11:03:59 T:140735739491264   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/
11:03:59 T:140735739491264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/) failed

**Comment by mansj** [comment]
+1 on this error, but in Fire TV Kodi 16.1 Jarvis. 

`12:39:09 T:18446744072502175576   DEBUG: -->Python Interpreter Initialized<--
12:39:09 T:18446744072502175576   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/default.py"
12:39:09 T:18446744072502175576   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.parsedom/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/:/data/app/org.xbmc.kodi-2/base.apk/assets/python2.6/lib/python26.zip:/data/app/org.xbmc.kodi-2/base.apk/assets/python2.6/lib/python2.6:/data/app/org.xbmc.kodi-2/base.apk/assets/python2.6/lib/python2.6/plat-linux3:/data/app/org.xbmc.kodi-2/base.apk/assets/python2.6/lib/python2.6/lib-tk:/data/app/org.xbmc.kodi-2/base.apk/assets/python2.6/lib/python2.6/lib-old:/data/app/org.xbmc.kodi-2/base.apk/assets/python2.6/lib/python2.6/lib-dynload
12:39:09 T:18446744072502175576   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay
12:39:09 T:18446744072502175576   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/default.py): instantiating addon using automatically obtained id of "plugin.video.svtplay" dependent on version 2.14.0 of the xbmc.python api
12:39:10 T:18446744072502175576   DEBUG: CommonFunctions-2.5.1
12:39:10 T:18446744072502175576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name OrderedDict
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/default.py", line 16, in <module>
                                                import resources.lib.FavoritesManager as FavoritesManager
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py", line 4, in <module>
                                                from collections import OrderedDict
                                            ImportError: cannot import name OrderedDict
                                            -->End of Python script error report<--
12:39:10 T:18446744072491782288   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
12:39:10 T:18446744072502175576    INFO: Python script stopped
12:39:10 T:18446744072502175576   DEBUG: Thread LanguageInvoker 18446744072502175576 terminating
12:39:10 T:18446744072491782288   DEBUG:  bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - plugin exited prematurely - terminating
12:39:10 T:18446744072491782288   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.svtplay/
12:39:10 T:18446744072491782288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/) failed
12:39:10 T:18446744072491782288   DEBUG: CGUIMediaWindow::GetDirectory ()
12:39:10 T:18446744072491782288   DEBUG:   ParentPath = [plugin://plugin.video.svtplay/]
12:39:10 T:18446744072520894696   DEBUG: Thread BackgroundLoader start, auto delete: false
12:39:10 T:18446744072520894696   DEBUG: Thread BackgroundLoader 18446744072520894696 terminating
12:39:24 T:18446744072491782288    INFO: void XCURL::DllLibCurlGlobal::CheckIdle() - Closing session to http://feeds.xbmc.org (easy=0xb82f8e20, multi=0xb82f15b0)
12:39:26 T:18446744072491782288   DEBUG: SECTION:UnloadDelayed(DLL: libImageLib-arm.so)
12:39:36 T:18446744072502654424   DEBUG: Thread JobWorker 18446744072502654424 terminating (autodelete)
12:39:36 T:18446744072501929416   DEBUG: Thread JobWorker 18446744072501929416 terminating (autodelete)
12:39:36 T:18446744072513721176   DEBUG: Thread JobWorker 18446744072513721176 terminating (autodelete)
`

**Comment by linqcan** [comment]
Looks like "OrderedDict" is not availble on all platforms in v16, but will be in v17.
I will revert this change for now as it doesn't fix any broken features. The favoirtes handling will be rewritten for v17.

CC @allwi290

**Comment by allwi290** [comment]
Thumbs up

**Comment by linqcan** [comment]
https://github.com/xbmc/repo-plugins/pull/785
v4.0.38 should enable favorites for you again, let me know if it doesn't.
