### ISSUE TITLE
Only listing some of the episodes available

### ISSUE THREAD

**Issue by jensbengtsson** [kodi-svtplay/xbmc-svtplay#179]
When listing episodes for a show I only get some of the episodes. Shows that have 20ish episodes available only show some of them. This started occurring in the last 5 days.

**Comment by linqcan** [comment]
Please state steps required to reproduce. I.e, what show(s) etc?

**Comment by jensbengtsson** [comment]
We start the app, go to Programs (from my head, don't know the exact menu name, it's a list of all shows), pick the show Greta Gris. There's two episodes listed. 
But on the page http://www.svtplay.se/greta-gris there are several more then two. 

This is on OpenELEC (official) Version: 6.0.3 

<addon id="plugin.video.svtplay"
       name="SVT Play"
       version="4.0.38"
       provider-name="nilzen">

**Comment by linqcan** [comment]
Thanks for the additional information.

Not seeing this in v4.0.38.
Program A-Ö -> Greta Gris
![screenshot_2016-12-12_21-58-56](https://cloud.githubusercontent.com/assets/832984/21117475/2abc9908-c0ba-11e6-9193-dbfb8b55b93b.png)

What version of the plugin are you running?

**Comment by jensbengtsson** [comment]
It's the latest version. I will try to reinstall the plugin later today and see if that solves it.

**Comment by jensbengtsson** [comment]
I uninstalled and installed again. It's v4.0.38.

Now when I try to list episodes it only shows "clips".

**Comment by linqcan** [comment]
Still works here. I need a log from you. Please enable debugging in the add-on's settings as well.
http://kodi.wiki/view/Log_file/Easy

**Comment by jensbengtsson** [comment]
http://pastebin.com/q5vu5bGW

Only got one episode listed although there should be more.

**Comment by linqcan** [comment]
Can't say from the log why you can't see them. According to the log the query returned 15 items:
```
20:52:48  38.636505 T:1967509504   DEBUG: Saving fileitems [plugin://plugin.video.svtplay/?mode=pr&url=%2fgreta-gris]
20:52:48  38.639027 T:1967509504   DEBUG:   -- items: 15, sort method: 0, ascending: false
```

Have you filtering (or something similar) on by accident?

**Comment by jensbengtsson** [comment]
I had a look at the filtering menu and "hide watched" was checked. I guess this is what happens when you're 2 and 5 year old kids get a a hold of the remote. 

I'm so sorry for taking up your time with this. Thank you for your help.

**Comment by linqcan** [comment]
No worries! Glad it got solved!
