### ISSUE TITLE
Plugin crash - empty xml

### ISSUE THREAD

**Issue by gostaj** [kodi-svtplay/xbmc-svtplay#18]
Seems like the plugin is dependent upon info in this xml:

http://svtplay.se/mobil/deviceconfiguration.xml

Unfortunately that XML is empty so the plugin crashes.

**Comment by wippie** [comment]
It seems SVT's own developers has been noted about this issue:

http://kontakt.svtplay.se/org/svt-play/d/fil-trasig-httpsvtplaysemobildeviceconfigurationxm/

**Comment by nilzen** [comment]
I'm working on a new version that scrapes the site instead, will require a recent xbmc build since it needs to support HLS.
