### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#181]
Travis reports issue with the API, however, local tests show no issue.
https://travis-ci.org/linqcan/xbmc-svtplay/builds/186125572

Though it seems like they are about to switch to a paginated API:
episodes_from_title?title=agenda&page=1
clips_from_title?title=agenda&page=1

Heads up...

**Comment by Mart75** [comment]
Cannot get full listing of episodes. 
In this case Julkalendern:
http://svtplay.se/api/video_title_page;title=/julkalendern-selmas-saga only shows episode 1 to 21.

This will give all results:
www.svtplay.se/api/episodes_from_title?title=julkalendern-selmas-saga&page=1, gives episodes 23-8
www.svtplay.se/api/episodes_from_title?title=julkalendern-selmas-saga&page=2, gives episodes 7-1

This row can be found close to the end of the string:
{"currentPage":1,"nextPageUrl":"/julkalendern-selmas-saga/hela-program?sida=2","totalPages":2}

**Comment by linqcan** [comment]
Hmm, so they did actually start to change the backend...
I am unable to fix and/or deploy until after the Christmas weekend,
unfortunately.
Until then I have to refer to the official web app and their native mobile
apps.
Sorry for the inconvenience!

**Comment by Mart75** [comment]
I changed getEpisodes (see code below) and now series with episodes seems to work. Other programs as "Dokument utifrån" gives errors. I do not fully understand how the plugin works and have nothing to go on to get further. (Kids are happy now when "Julkalendern" works again).

Sorry to post code here but I'm not that handy with GitHub.


```python
def getEpisodes(title):
  """
  Returns the episodes for a program URL.
  """
  common.log("The title: "+title)
  url = BASE_URL+API_URL+"episodes_from_title?title="+title + "&page=1"
  r = requests.get(url)
  if r.status_code != 200:
    common.log("Could not get JSON for "+url)
    return None
  programs = []
  pages = r.json()["paginationData"]["totalPages"]
  for k in range(1, pages+1):
    if k != 1:
      url = BASE_URL+API_URL+"episodes_from_title?title="+title+"&page="+str(k)
      r = requests.get(url)
    for item in r.json()["videos"]:
      program = {}
      program["title"] = item["programTitle"]+" - "+item["title"]
      program["url"] = item["contentUrl"]
      program["thumbnail"] = helper.prepareThumb(item.get("thumbnail", ""), BASE_URL)
      info = {}
      info["plot"] = item.get("description", "")
      info["fanart"] = helper.prepareFanart(item.get("poster", ""), BASE_URL)
      program["info"] = info
      programs.append(program)
  return programs
```

**Comment by linqcan** [comment]
Glad that you got it working,  thanks for sharing! Ä
I will fix this this after Christmas. God jul!

**Comment by Mart75** [comment]
OK so i could not let it go.
Edited this but it's a hack. Now things play without breaking (what I have seen so far).
Listings becomes a mess in some categories instead. Now there is no more time for this...
God Jul!

```python
def viewCategory(genre):
  programs = svt.getProgramsForGenre(genre)
  if not programs:
    return
  for program in programs:
    if (program["url"][:7] == "/video/"):
      createDirItem(program, MODE_VIDEO)
    else:
      addDirectoryItem(program["title"], { "mode" : MODE_PROGRAM, "url" : program["url"] }, thumbnail=program["thumbnail"], info=program["info"])
```
