### ISSUE TITLE
Particular stream fails to play

### ISSUE THREAD

**Issue by keab** [kodi-svtplay/xbmc-svtplay#182]
This may be a server issue rather than a bug, but I experienced today that one particular stream failed to play - I haven't found any other stream not working, but I haven't tried more than about five different.  I did try the same m3u8 link as below in my web browser and got the stream showing in the VLC player, so the SVT server seems to be working. 

`23:26:59 T:2803303488  NOTICE: [SVT Play 4.0.39] <module> : '{'url': '%2Fvideo%2F11712046%2Fgrantchester-julspecial%2Fgrantchester-julspecial-avsnitt-1', 'mode': 'video'}'
23:27:00 T:2803303488  NOTICE: [SVT Play 4.0.39] hlsStrip : 'Stripping file: https://svtplay3f-f.akamaihd.net/i/se/secure/20161228/1376445-001A/PG-1376445-001A-GRANTCHESTERCHR-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1376445-001A.m3u8'
23:27:00 T:2803303488  NOTICE: [SVT Play 4.0.39] hlsStrip : 'Returned stream url : https://svtplay3f-f.akamaihd.net/i/se/secure/20161228/1376445-001A/PG-1376445-001A-GRANTCHESTERCHR-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null=0&id=AgCwCvn1T4g9HLSNZVjIHRrv+6S+gcG9KDyxkMa52XH%2fnRbQxDun6dsXe3CRPfgJXgChq0LDz+gsgg%3d%3d'
23:27:00 T:2803303488 WARNING: Attempt to use invalid handle 26
23:27:01 T:3037929472  NOTICE: DVDPlayer: Opening: https://svtplay3f-f.akamaihd.net/i/se/secure/20161228/1376445-001A/PG-1376445-001A-GRANTCHESTERCHR-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null=0&id=AgCwCvn1T4g9HLSNZVjIHRrv+6S+gcG9KDyxkMa52XH%2fnRbQxDun6dsXe3CRPfgJXgChq0LDz+gsgg%3d%3d
23:27:01 T:3037929472 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
23:27:01 T:2803303488  NOTICE: Thread DVDPlayer start, auto delete: false
23:27:01 T:2803303488  NOTICE: Creating InputStream
23:27:01 T:2891969600  NOTICE: Thread FileCache start, auto delete: false
23:27:02 T:2803303488  NOTICE: Creating Demuxer
23:27:02 T:2803303488   ERROR: OpenDemuxStream - Error creating demuxer
23:27:02 T:2803303488  NOTICE: CDVDPlayer::OnExit()
23:27:02 T:3037929472   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.svtplay/?url=%2Fvideo%2F11712046%2Fgrantchester-julspecial%2Fgrantchester-julspecial-avsnitt-1&mode=video]
`

**Comment by linqcan** [comment]
You are using the bandwidth selector, which can have this size effect since
not all URLs created are Kodi friendly. If you turn off manual bandwidth
you should not have this issue (?).

**Comment by keab** [comment]
Strange, I had the "Don't use avcl...streams" setting active, and with that active you can't select manual bandwidth (greyed out, not marked). I have tried without the avcl-setting and with/without manual bandwith. No combination working with that particular stream.

**Comment by linqcan** [comment]
Ok, good info!
Will check to see if this is a new pattern or fluke in the SVT cms.

**Comment by linqcan** [comment]
Tried with and without the "Don't use avc1.."" setting and it "works here" (tm).
Kodi 17 RC1

**Comment by linqcan** [comment]
Is this still a problem for you?

**Comment by keab** [comment]
Yesterday I upgraded to Kodi r16 and it seems to work now. 
The automatic upgrades had stopped for some reason.

---- Erik Lindqvist skrev ----
