### ISSUE TITLE
All shows just shows 'klipp..'

### ISSUE THREAD

**Issue by ogr3** [kodi-svtplay/xbmc-svtplay#184]
Starting on Christmas eve, 'julkalendern' stopped working as a favorite, only showing 'klipp..', and now all kids shows exhibit the same problem.

General change in CMS on svt? All episodes show up in svt play app.

**Comment by linqcan** [comment]
Which version are you running?
The latest, 4.0.40 should solve this problem.

**Comment by ogr3** [comment]
4.0.39 - has 4.0.40 rolled out? Running osmc on a vero2 using the official kodi repositories.

**Comment by linqcan** [comment]
Yep. Was pulled in during the night I think.
http://mirrors.xbmc.org/addons/gotham/plugin.video.svtplay/

**Comment by linqcan** [comment]
Update 4.0.40 should solve this. Closing.
