### ISSUE TITLE
Some media fails to play after Krypton upgrade

### ISSUE THREAD

**Issue by ogr3** [kodi-svtplay/xbmc-svtplay#188]
I run a Vero 2 media player that just got the Krypton upgrade to Kodi.

After the upgrade some streams fail to show, e.g. 'Djupet'. I just get a counter telling that the stream has started, but no video. If I back all the way back i see a garbled image.

Most streams from SVT still play fine. Any Ideas as to what is different with this stream and why it doesn't work in Krypton?

**Comment by linqcan** [comment]
Hmm, sounds strange yes. Will look at it!

**Comment by ogr3** [comment]
Seems like it is a platform issue:

https://discourse.osmc.tv/t/some-media-fails-to-play-after-krypton-upgrade/22151/17

It works fine in an RPI3 and a Vero, and after some patches it seems to work fine on Vero 2 as well.

**Comment by linqcan** [comment]
OK, thanks for reporting!
