### ISSUE TITLE
Melodifestivalen opens live channel...

### ISSUE THREAD

**Issue by Mart75** [kodi-svtplay/xbmc-svtplay#190]
When trying to play Melidifestivalen first episode a live channel start instead. The other videos in the listing works as expected.

**Comment by linqcan** [comment]
The first episode in the listing is a (no yet boradcasted) live stream for Februray 11, right?
I think this is inteded behavior, SVT publish, at times, the show data before the broadcast (that's why you can see it).

**Comment by perstar** [comment]
I haven't checked if there's something else there now, but when I tried to watch that first episode of Melodifestivalen the day after it was sent I couldn't watch it with xbmc-svtplay, but received something else (sports) that was sent live then (I think) or maybe had been sent live later.

**Comment by linqcan** [comment]
It unfortunate but this is how it is sometimes, can't really do anything as we only present what is in their listings. Sorry...
Hope you're enoying the plugin anyway!
