### ISSUE TITLE
Feature request: filter programs for foreign countries

### ISSUE THREAD

**Issue by herrJones** [kodi-svtplay/xbmc-svtplay#191]
Hi,

is it possible to add the filter: _kan ses utomlands_ ? (as found on : http://www.svtplay.se/program)
I live in Belgium and it'd be nice to see only the programs I can start. 
Or at least: notify with an icon or grey-out the programs I cannot see.

Thanks,

   Jan

**Comment by linqcan** [comment]
Thanks for the suggestion. Will look into this!

**Comment by linqcan** [comment]
Dev note:
```
title.onlyAvailableInSweden
```
or
```
videoPlayer.onlyAvailableInSweden
```

Settings option; "Hide content not available outside of Sweden"

**Comment by linqcan** [comment]
I haven't forgotten about this, higher priority items (lisitng and playback broke..) have kept this feature back.

**Comment by herrJones** [comment]
No problem, no hurry :-)

**Comment by linqcan** [comment]
Not forgotten. I have to remove some code first before I add any new stuff.

**Comment by linqcan** [comment]
Woop woop, ready!
Will show up in the next release. You can toggle it in the Addon's settings.

**Comment by asplundj** [comment]
Excellent new feature, thanks! Would it also be possible to filter out the folders that only contains streams that only can be watched from Sweden.

**Comment by linqcan** [comment]
@asplundj Looks doable, will open a separate issue for that.
