### ISSUE TITLE
Can't play news broadcasts, rapport for example

### ISSUE THREAD

**Issue by sarahgustafsson** [kodi-svtplay/xbmc-svtplay#192]
Hi,

Since upgrading to Kodi 17.0 (LibreElec) I've been having problems with the sound being out of sync, by approx 5sec, been syncing manually, when watching live streams.

Today I can't play news broadcasts like rapport at all.

Kind Regards
Sarah

**Comment by linqcan** [comment]
Hi,
Thanks for reporting this!

Do you see any error messages?
Would it be possible for you to provide a log?

**Comment by ToddeSwe** [comment]
Hi
Here you go: http://pastebin.com/ayB4RZ2y

**Comment by linqcan** [comment]
Thanks!
Seems like there are a lot of things breaking right now, this being one of them.

**Comment by ToddeSwe** [comment]
Major update maybe :)

 

Från: Erik Lindqvist [mailto:notifications@github.com] 
Skickat: den 7 mars 2017 18:51
Till: nilzen/xbmc-svtplay <xbmc-svtplay@noreply.github.com>
Kopia: ToddeSwe <toddeswe@gmail.com>; Comment <comment@noreply.github.com>
Ämne: Re: [nilzen/xbmc-svtplay] Can't play news broadcasts, rapport for example (#192)

 

Thanks!
Seems like there are a lot of things breaking right now, this being one of them.

**Comment by sarahgustafsson** [comment]
Here you go

http://sprunge.us/fHAa
http://pastebin.com/tQczu4Km

**Comment by linqcan** [comment]
Thanks for the logs!
Rework is needed due to site changes, see #193 .

**Comment by linqcan** [comment]
See #193 .

**Comment by ToddeSwe** [comment]
Hej

 

Hur kan jag ladda ner den innan den hamnar på reopon?

 

Från: Erik Lindqvist [mailto:notifications@github.com] 
Skickat: den 11 mars 2017 21:47
Till: nilzen/xbmc-svtplay <xbmc-svtplay@noreply.github.com>
Kopia: ToddeSwe <toddeswe@gmail.com>; Comment <comment@noreply.github.com>
Ämne: Re: [nilzen/xbmc-svtplay] Can't play news broadcasts, rapport for example (#192)

 

Closed #192 <https://github.com/nilzen/xbmc-svtplay/issues/192> .

**Comment by linqcan** [comment]
You'd have to download the source (from this Github project)  and re-pack it like the official distribution is packed. Then install it manually.

Official distributions: http://mirrors.xbmc.org/addons/gotham/plugin.video.svtplay/
http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by ToddeSwe** [comment]
Can’t find the latest 4.0.43

 

Från: Erik Lindqvist [mailto:notifications@github.com] 
Skickat: den 11 mars 2017 22:03
Till: nilzen/xbmc-svtplay <xbmc-svtplay@noreply.github.com>
Kopia: ToddeSwe <toddeswe@gmail.com>; Comment <comment@noreply.github.com>
Ämne: Re: [nilzen/xbmc-svtplay] Can't play news broadcasts, rapport for example (#192)

 

You'd have to download the source (from this Github project) and re-pack it like the official distribution is packed. Then install it manually.

Official distributions: http://mirrors.xbmc.org/addons/gotham/plugin.video.svtplay/
http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by linqcan** [comment]
https://github.com/nilzen/xbmc-svtplay/archive/v4.0.43.zip

Again, you have to repackage the ZIP file so that it looks like the real archives (see v4.0.42 from the xbmc repo I posted previously), specifically; the folder in the ZIP file must be named "plugin.video.svtplay".

**Comment by sarahgustafsson** [comment]
Has anyone been able to retrieve the latest package from the official repo yet? Because I wasn't able to repackage it correctly.

**Comment by ToddeSwe** [comment]
Yes i managed to get it and it works fine. 

Get Outlook for iOS




On Sat, Mar 18, 2017 at 3:00 PM +0100, "sarahgustafsson" <notifications@github.com> wrote:












Has anyone been able to retrieve the latest package from the official repo yet? Because I wasn't able to repackage it correctly.
