### ISSUE TITLE
All choices cause plugin error

### ISSUE THREAD

**Issue by castalla** [kodi-svtplay/xbmc-svtplay#195]
All choices broken.

**Comment by linqcan** [comment]
Please elaborate. "Works here".
What version are you running?

**Comment by tomtefan** [comment]
I have the same problem, kodi 17.1 (libreelec). I'm not seeing anything useful in the logs though, only something like this:

19:52:52.241 T:140514264971392   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.svtplay/?url=1134318-003&mode=video]

**Comment by tomtefan** [comment]
Some more info:

22:26:31.264 T:140512197605120 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.svtplay/?mode=playlist-manager
22:26:31.264 T:140512197605120   ERROR: InputStream: Error opening, plugin://plugin.video.svtplay/?mode=playlist-manager
22:26:35.492 T:140512172951296  NOTICE: [SVT Play 4.0.45] <module> : 'params: {'mode': 'latest'}'
22:26:46.546 T:140511977916160  NOTICE: [SVT Play 4.0.45] <module> : 'params: {'url': '1134318-003', 'mode': 'video'}'
22:26:46.673 T:140511977916160  NOTICE: [SVT Play 4.0.45] __get_video_json_for_video_id : 'ERROR: Could not fetch video data for URL http://api.svt.se/videoplayer-api/video/'
22:26:46.674 T:140511977916160  NOTICE: [SVT Play 4.0.45] startVideo : 'ERROR: Could not get video JSON'
22:26:46.980 T:140514264971392  NOTICE: VideoPlayer: Opening:
22:26:46.980 T:140514264971392 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:26:46.980 T:140511977916160  NOTICE: Creating InputStream
22:26:46.981 T:140511977916160   ERROR: Error on dvdnav_open
22:26:46.981 T:140511977916160   ERROR: CVideoPlayer::OpenInputStream - error opening []
22:26:46.981 T:140511977916160  NOTICE: CVideoPlayer::OnExit()
22:26:46.981 T:140514264971392   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.svtplay/?url=1134318-003&mode=video]
