### ISSUE TITLE
"Livesändningar" not working

### ISSUE THREAD

**Issue by nilzen** [kodi-svtplay/xbmc-svtplay#2]

**Comment by TsUPeR** [comment]
I had to 

```
if not ".mp4" in videolink[4][0]:
    item.setProperty("IsLive", "true")
xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(videolink[4][0], item)
```

**Comment by nilzen** [comment]
Great! I will have a look at it tonight, or have you fixed it in your fork?

**Comment by TsUPeR** [comment]
Nope, havnt started yet. This was from my "old" source...

**Comment by nilzen** [comment]
I've fixed so the list at east renders now, but no live streams atm so i can't test if i need to set the "IsLive" property or not, neither can i find any documentation what it does.

**Comment by TsUPeR** [comment]
I found it here http://trac.xbmc.org/ticket/8971

**Comment by nilzen** [comment]
Seems to work after the merge nilzen/xbmc-svtplay@28856dd6ab7be6988374
