### ISSUE TITLE
Channels are missing 

### ISSUE THREAD

**Issue by ToddeSwe** [kodi-svtplay/xbmc-svtplay#204]
In channels section I miss 2 of them. Svt 2 and Kunskapskanalen.

**Comment by linqcan** [comment]
Are they always gone? The channel section is dynamic and only shows the
channels that are currently broadcasting.

**Comment by ToddeSwe** [comment]
Yesterday they where gone. And today but now when I look they're there. ☺️ Have never seen this behavior before and I use your addonn on a daily basis.

**Comment by linqcan** [comment]
It's new. SVT has a new dynamic way (TV guide) of displaying channels on
their website.

**Comment by ToddeSwe** [comment]
That explains why I haven't seen it before. 😃 Glad Påsk!!
