### ISSUE TITLE
Cannot get svt-play to start playing stuff on raspberry3 with Kodi 17

### ISSUE THREAD

**Issue by malmenh** [kodi-svtplay/xbmc-svtplay#209]
Svtplay has not worked for months now and for every new update I hope to get it started. I get this error in the log:

22:40:13.545 T:1510519712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 293, in <module>
                                                startVideo(ARG_URL)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 214, in startVideo
                                                show_obj = helper.resolveShowJSON(video_json)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/helper.py", line 339, in resolveShowJSON
                                                video_url = cleanUrl(video_url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/helper.py", line 348, in cleanUrl
                                                tmp = video_url.split("?")
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--

**Comment by fusielec** [comment]
Have exactly the same issue on raspberry 3!

**Comment by linqcan** [comment]
Do you still have the issue with the latest version? 
Latest version as of June 4 is 4.0.50
Please check that you are running the latest version and report back here.

**Comment by malmenh** [comment]
Thank you for looking into this. When I started this thread I was running 4.0.49 and nothing worked. Now I run 4.0.50 on Kodi 17.1 and a few things actually works now! About 30% I would say. This is the best result for months so it is a big step. "Kanaler" (live viewing) is not working at all and "Senaste program" works about 30% of the items. Thank you for working on this. Its a wonderful thing when it works! :)

**Comment by linqcan** [comment]
Please submit a new log with debug enabled in the addon settings. Also, add
step by step instructions for reproducing the issue. Thank you!

**Comment by malmenh** [comment]
Ok I will make a log of trying to watch "Kanaler" and SVT1. More details with log...

**Comment by malmenh** [comment]
Ok, turned on debug, restarted, goto "tillägg", "SVTPlay", try to start "Kanaler" and "SVT1".

20:11:55.142 T:1946624016  NOTICE: special://profile/ is mapped to: special://masterprofile/
20:11:55.142 T:1946624016  NOTICE: -----------------------------------------------------------------------
20:11:55.142 T:1946624016  NOTICE: Starting Kodi (17.1 Git:39e9963). Platform: Linux ARM 32-bit
20:11:55.142 T:1946624016  NOTICE: Using Unknown Kodi x32 build (version for Raspberry Pi)
20:11:55.142 T:1946624016  NOTICE: Kodi compiled Apr 30 2017 by GCC 6.3.0 for Linux ARM 32-bit version 4.9.25 (264473)
20:11:55.142 T:1946624016  NOTICE: Running on OpenELEC (official) - Version: 8.0.3, kernel: Linux ARM 32-bit version 4.9.25
20:11:55.142 T:1946624016  NOTICE: FFmpeg version/source: 3.2.4
20:11:55.142 T:1946624016  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
20:11:55.142 T:1946624016  NOTICE: ARM Features: Neon enabled
20:11:55.142 T:1946624016  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi/
20:11:55.142 T:1946624016  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
20:11:55.142 T:1946624016  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
20:11:55.142 T:1946624016  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
20:11:55.142 T:1946624016  NOTICE: special://envhome/ is mapped to: /storage
20:11:55.142 T:1946624016  NOTICE: special://home/ is mapped to: /storage/.kodi
20:11:55.142 T:1946624016  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
20:11:55.142 T:1946624016  NOTICE: special://logpath/ is mapped to: /storage/.kodi/temp
20:11:55.142 T:1946624016  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
20:11:55.143 T:1946624016  NOTICE: Local hostname: Kodi
20:11:55.143 T:1946624016  NOTICE: Log File is located: /storage/.kodi/temp//kodi.log

----------------

20:12:11.988 T:1500509088   DEBUG: RunQuery took 6 ms for 2 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=28 ORDER BY sets.idSet
20:12:12.014 T:1500509088   DEBUG: RunQuery took 3 ms for 2 items query: select * from movie_view  WHERE movie_view.idSet = 28
20:12:12.048 T:1946624016   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.svtplay/)
20:12:12.048 T:1946624016   DEBUG:   ParentPath = [plugin://plugin.video.svtplay/]
20:12:12.058 T:1500509088   DEBUG: RunQuery took 4 ms for 1 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=29 ORDER BY sets.idSet
20:12:12.078 T:1500509088   DEBUG: RunQuery took 3 ms for 1 items query: select * from movie_view  WHERE movie_view.idSet = 29
20:12:12.084 T:1446519712   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.svtplay] took 36 ms
20:12:12.085 T:1859122080   DEBUG: StartScript - calling plugin SVT Play('plugin://plugin.video.svtplay/','1','')
20:12:12.085 T:1492120480   DEBUG: Thread LanguageInvoker start, auto delete: false
20:12:12.085 T:1492120480    INFO: initializing python engine.
20:12:12.085 T:1492120480   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.svtplay/default.py): start processing
20:12:12.125 T:1492120480   DEBUG: -->Python Interpreter Initialized<--
20:12:12.125 T:1492120480   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.svtplay/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.svtplay/default.py"
20:12:12.126 T:1492120480   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.svtplay/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.svtplay:/storage/.kodi/addons/script.module.parsedom/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
20:12:12.126 T:1492120480   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.svtplay/default.py): entering source directory /storage/.kodi/addons/plugin.video.svtplay
20:12:12.126 T:1492120480   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.svtplay/default.py): instantiating addon using automatically obtained id of "plugin.video.svtplay" dependent on version 2.14.0 of the xbmc.python api
20:12:12.128 T:1500509088   DEBUG: RunQuery took 4 ms for 1 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=30 ORDER BY sets.idSet
20:12:12.148 T:1500509088   DEBUG: RunQuery took 2 ms for 1 items query: select * from movie_view  WHERE movie_view.idSet = 30
20:12:12.187 T:1500509088   DEBUG: RunQuery took 4 ms for 1 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=31 ORDER BY sets.idSet
20:12:12.207 T:1500509088   DEBUG: RunQuery took 3 ms for 1 items query: select * from movie_view  WHERE movie_view.idSet = 31
20:12:12.258 T:1500509088   DEBUG: RunQuery took 5 ms for 1 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=32 ORDER BY sets.idSet
20:12:12.278 T:1500509088   DEBUG: RunQuery took 3 ms for 1 items query: select * from movie_view  WHERE movie_view.idSet = 32
20:12:12.319 T:1500509088   DEBUG: RunQuery took 5 ms for 1 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=33 ORDER BY sets.idSet
20:12:12.339 T:1500509088   DEBUG: RunQuery took 3 ms for 1 items query: select * from movie_view  WHERE movie_view.idSet = 33
20:12:12.388 T:1500509088   DEBUG: RunQuery took 5 ms for 2 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=34 ORDER BY sets.idSet
20:12:12.409 T:1500509088   DEBUG: RunQuery took 3 ms for 2 items query: select * from movie_view  WHERE movie_view.idSet = 34
20:12:12.411 T:1492120480   DEBUG: CommonFunctions-2.5.1
20:12:12.488 T:1500509088   DEBUG: RunQuery took 4 ms for 2 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=35 ORDER BY sets.idSet
20:12:12.509 T:1500509088   DEBUG: RunQuery took 3 ms for 2 items query: select * from movie_view  WHERE movie_view.idSet = 35
20:12:12.552 T:1946624016   DEBUG: ------ Window Init (DialogBusy.xml) ------
20:12:12.593 T:1500509088   DEBUG: RunQuery took 24 ms for 1 items query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet WHERE sets.idSet=36 ORDER BY sets.idSet
20:12:12.617 T:1500509088   DEBUG: RunQuery took 3 ms for 1 items query: select * from movie_view  WHERE movie_view.idSet = 36
20:12:12.772 T:1500509088   DEBUG: Skin Helper Service --> Ended Background worker...
20:12:12.980 T:1492120480    INFO: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.svtplay/default.py): script successfully run
20:12:12.996 T:1946624016   DEBUG: RunQuery took 3 ms for 0 items query: SELECT * FROM tvshow_view  WHERE idParentPath=1
20:12:12.999 T:1500509088   DEBUG: Thread BackgroundLoader start, auto delete: false
20:12:13.019 T:1500509088   DEBUG: Thread BackgroundLoader 1500509088 terminating
20:12:13.121 T:1492120480    INFO: Python script stopped
20:12:13.121 T:1492120480   DEBUG: Thread LanguageInvoker 1492120480 terminating
20:12:13.212 T:1946624016   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
20:12:14.395 T:1783530400   DEBUG: PushCecKeypress - received key a7 duration 0 (rep:0 size:0)
20:12:14.395 T:1783530400   DEBUG: PushCecKeypress - added key a7
20:12:14.405 T:1946624016   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down

---------------------------

20:12:21.814 T:1946624016   DEBUG: StartScript - calling plugin SVT Play('plugin://plugin.video.svtplay/','3','?url=ch-svt1&mode=video')
20:12:21.814 T:1402495904   DEBUG: Thread LanguageInvoker start, auto delete: false
20:12:21.815 T:1402495904    INFO: initializing python engine.
20:12:21.815 T:1402495904   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.svtplay/default.py): start processing

---------------------

20:12:21.848 T:1402495904   DEBUG: -->Python Interpreter Initialized<--
20:12:21.848 T:1402495904   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.svtplay/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.svtplay/default.py"
20:12:21.849 T:1402495904   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.svtplay/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.svtplay:/storage/.kodi/addons/script.module.parsedom/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
20:12:21.849 T:1402495904   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.svtplay/default.py): entering source directory /storage/.kodi/addons/plugin.video.svtplay
20:12:21.849 T:1402495904   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.svtplay/default.py): instantiating addon using automatically obtained id of "plugin.video.svtplay" dependent on version 2.14.0 of the xbmc.python api  
20:12:21.867 T:1741587360   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"title":"Barnmorskan i East End","type":"movie"},"playlistid":1,"position":0}

-----------

20:12:22.710 T:1402495904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 293, in <module>
                                                startVideo(ARG_URL)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 214, in startVideo
                                                show_obj = helper.resolveShowJSON(video_json)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/helper.py", line 339, in resolveShowJSON
                                                video_url = cleanUrl(video_url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/helper.py", line 348, in cleanUrl
                                                tmp = video_url.split("?")
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--

-----------------------

20:12:22.874 T:1946624016   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.svtplay/?url=ch-svt1&mode=video]
20:12:22.874 T:1946624016   DEBUG: Playlist Player: no more playable items... aborting playback


-------------------------------

20:12:26.639 T:1946624016   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.svtplay/)
20:12:26.639 T:1946624016   DEBUG:   ParentPath = [plugin://plugin.video.svtplay/]
20:12:26.678 T:1859122080   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.svtplay] took 38 ms
20:12:26.679 T:1446519712   DEBUG: StartScript - calling plugin SVT Play('plugin://plugin.video.svtplay/','4','')
20:12:26.679 T:1500509088   DEBUG: Thread LanguageInvoker start, auto delete: false
20:12:26.679 T:1500509088    INFO: initializing python engine.
20:12:26.679 T:1500509088   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.svtplay/default.py): start processing
20:12:26.712 T:1500509088   DEBUG: -->Python Interpreter Initialized<--
20:12:26.712 T:1500509088   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.svtplay/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.svtplay/default.py"
20:12:26.713 T:1500509088   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.svtplay/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.svtplay:/storage/.kodi/addons/script.module.parsedom/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
20:12:26.713 T:1500509088   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.svtplay/default.py): entering source directory /storage/.kodi/addons/plugin.video.svtplay
20:12:26.713 T:1500509088   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.svtplay/default.py): instantiating addon using automatically obtained id of "plugin.video.svtplay" dependent on version 2.14.0 of the xbmc.python api
20:12:26.788 T:1716421536   DEBUG: CSMBFile::Close closing fd 10000

-----------------------------------

Hope I caught the issue in those lines.

**Comment by malmenh** [comment]
Ok I have found what my issue was.

NOTICE: [SVT Play 4.0.50] getStreamForBW : 'No stream found for bandwidth setting 1600'

I remember locking bandwith to 1600 to keep it from constantly change from bad to good quallity playback. This was done several months ago. Now everything works :)

**Comment by linqcan** [comment]
Ah, good. The bandwidth locker is not stable enough and I am about to
remove it in a future release. Glad it is working for you now!

**Comment by malmenh** [comment]
It could be a nice thing to have then it jumps between bandwith rates all the time and drives you crazy. Maybe just add a warning to the GUI what is causing this error? Like 'No stream found for bandwidth setting 1600' would be very helpful to the user. Thanks again for a great app!

**Comment by linqcan** [comment]
Good suggestion!
Will close this issue and open a new one with this suggestion.

**Comment by linqcan** [comment]
See #210
