### ISSUE TITLE
Better error handling when manual bandwidth is used and no stream found

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#210]
Currently the user gets a cryptic crash/error message from Kodi.

Proposal: Add a dialog stating why the stream couldn't start if manual bandwidth selection is used and no stream was found.

**Comment by even-stephen** [comment]
Maybe just have "low, medium, high" option and have logic to pick what stream that should be used? (instead of specifying a specific bitrate (which is subject to change)).

An error dialog would then not be needed.

**Comment by linqcan** [comment]
Note to future me: Consider refactoring the manual bandwidth functionality so that it could easier be removed in the future (as well as re-inserted if it is still used).

Background: The manual bandwidth feature was once created for Apple TV (ATV) as it could not handle the high def streams at some point in time. Kodi on ATV is now dead.

**Comment by linqcan** [comment]
Closing as this feature is removed in v5.0.2
