### ISSUE TITLE
Videos placed in "Öppet Arkiv" not playing

### ISSUE THREAD

**Issue by Mart75** [kodi-svtplay/xbmc-svtplay#212]
Content that i think are placed in "Öppet Arkiv" but listed in the SVT PLAY addon (Reuter och Skoog, Potatishandlaren, Byhåla,...) do not play.
I think SVT have started adding content from "Öppet Arkiv" to the SVT PLAY website.

KODI logg show:
12:04:01.171 T:139967739529600   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.svtplay/?url=video%2F1355922-003&mode=video]

**Comment by linqcan** [comment]
Thanks for reporting.

Should probably try to hide these if they are not playable.

Adding to wishlist.

**Comment by Mart75** [comment]
Retrospect play these listings (in the svt play section) so I think it should be possible for the SVT Play add-on as well. I Have the retrospect add-on only to play things from "Öppet Arkiv" . If these listings were playable from the SVT Play add-on I would be more than happy! I vote for trying to play these items rather than hiding them... Then I can get rid of Retrospect. (On the other hand I'm not the one doing the work here...)
Thanks for looking after this Add-on!

**Comment by linqcan** [comment]
As per #76 "Öppet Arkiv" is handled by other addon(s) as it resides on a different domain and with a different backend. As it happens someone posted in #76 the other day advertising that they maintain an Öppet Arkiv addon (https://github.com/alexbjorling/kodi-svt-oppetarkiv).
To keep maintenance of this addon to the lowest the decision in #76 stands, Öppet Arkiv should be handled by its own addon.

**Comment by linqcan** [comment]
Tried Reuter&Skoog (as your log trace pointed to that one) and had no issues using version 4.0.51.
I just pushed 4.0.51 to Kodi (it should be rolling out to you in a day or so), let me know if you still have issues when you have tried with v4.0.51.

**Comment by Mart75** [comment]
Sorry for the delay.
Yes, now it works perfectly! Thanks!
