### ISSUE TITLE
"All videos" should be default for Channels

### ISSUE THREAD

**Issue by insurw** [kodi-svtplay/xbmc-svtplay#214]
I always have Kodi's "Unwatched" enabled. Doing so will return an empty list in Channels, if you've watched a channel, forcing you to toggle it to "All videos/Watched".

**Comment by linqcan** [comment]
Thank you for your report.
As you have discovered marking items as watched is a feature in Kodi and not in the plugin. As the channels themselves are video items to Kodi "Watched" will apply to them too. **I did try** to see if I could get Kodi to think the items were unwatched by manipulting metadata but it didn't work. So I think you have cope with it I am afraid. Sorry....

**Comment by insurw** [comment]
@linqcan 
Then do it like Retrospect. I haven't looked at the code but it looks like it clears the Watched status when you go back or leave the addon.
