### ISSUE TITLE
Clear Watched status for Channels (live) automatically

### ISSUE THREAD

**Issue by insurw** [kodi-svtplay/xbmc-svtplay#215]
The issue with getting an empty list for Channels with "Unwatched" enabled seems solved in Retrospect. I haven't checked the code but it looks like it clears the Watched status if you go back or leave the addon. It seemed to only affect the live channels. It's a bit hard to test as Retrospect's SVTPlay is semi-broken (he won't update/host anymore because he got scared of getting sued) but live channels and clearing Watched status still work.

**Comment by linqcan** [comment]
As you mentioned, Retrospect is dead and I haven't been able to parse through his code base yet. If you do and find anything useful please comment here or submit a Pull Request for me to review.

**Comment by linqcan** [comment]
Closing as I can't figure this one out. FWIW the "playcount" is set to 0 for all items so Kodi should recognize them as new but it seems to have no impact.

**Comment by insurw** [comment]
Retrospect has been alive for quite a while. So check their code/ask the devs. Though I never understood why that was a good reason to close this issue. You could've just asked for help in the forums.
