### ISSUE TITLE
X-forwarded-For

### ISSUE THREAD

**Issue by asplundj** [kodi-svtplay/xbmc-svtplay#222]
# Steps to reproduce
It would be nice if one could add an X-forwarded-For IP-address to the headers

# System information
Kodi version: 

Platform: 

Plugin version: 

# Log

**Comment by linqcan** [comment]
Why? I don't see any use case, could you elaborate?

**Comment by asplundj** [comment]
The user case is to be able to watch svt abroad

**Comment by linqcan** [comment]
That's not something this addon should provide. If you need this you are free to modify the addon code for yourself.
