### ISSUE TITLE
Very slow on Raspberry Pi 3 with Kodi - Any otehr experience this?

### ISSUE THREAD

**Issue by jpro-studio** [kodi-svtplay/xbmc-svtplay#223]
Very slow on Raspberry Pi 3 with Kodi 17

# Problem description
My Kodi takes 30-120 sec to list programs in SVTPlay now. It worked nice before but now is not good. 
# Steps to reproduce

# System information
Kodi version: 17.3
Platform: Raspberry Pi 3

Plugin version: latest as of 2018-09-13

**Comment by tuomaz** [comment]
Are you using ipv6? I had similar problems with ipv6 enabled.

**Comment by jpro-studio** [comment]
Ive reinstalled and now its better.
