### ISSUE TITLE
Not able to play latest episode.

### ISSUE THREAD

**Issue by MrSirMacke** [kodi-svtplay/xbmc-svtplay#230]
# Problem description
When I go to for example latest news program or "Vem vet mest?", the latest show will not play at all.
I tested via RetroSpect and it plays, but no sound.
Error in the plugins or Svtplay?

# Steps to reproduce

# System information
Kodi version: 
19.0 and same issue on 18.2

Platform: 
LibreElec

Plugin version: 
4.1

# Log

**Comment by MrSirMacke** [comment]
Steps to reproduce:
Just open latest news or for example Vem vet mest? and try to play the last show.

**Comment by linqcan** [comment]
I can't reproduce this on Kodi 18.2 on Android.

Please refer to your distribution's support (LibreElec).

**Comment by MrSirMacke** [comment]
I just tried reinstalling LibreElec on the NUC, it is the exact same issue on "Vem vet mest".
I also installed 18.2 and the addon on my Android 8.0 and the same issue is there!

See video of it here:
https://www.youtube.com/watch?v=uaHTMN9sQK0&list=PLdMrW7dy9rsudzUBIVFiFbU6Z-1qM1DMO&index=12

**Comment by MrSirMacke** [comment]
http://forumbilder.se/I5CD4/dsc-1664.JPG

**Comment by linqcan** [comment]
I still can't reproduce this, neither on Windows nor Android.

Are you able to capture a full log?
https://kodi.wiki/view/Log_file

**Comment by MrSirMacke** [comment]
Is this the log you want?
http://ix.io/1KYC

**Comment by linqcan** [comment]
@MrSirMacke Yes, that one looks good, thanks! Do you use proxy/vpn or some other non-standard setup?

**Comment by linqcan** [comment]
Entry point:
```
DEBUG: StartScript - calling plugin SVT Play('plugin://plugin.video.svtplay/','4','?url=1380769-020A&mode=video','resume:false')
```
Error:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 289, in <module>
                                                start_video(ARG_URL)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 223, in start_video
                                                show_obj = helper.resolveShowJSON(video_json)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/helper.py", line 157, in resolveShowJSON
                                                video_url = cleanUrl(video_url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/helper.py", line 166, in cleanUrl
                                                tmp = video_url.split("?")
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--
```

**Comment by MrSirMacke** [comment]
> 
> 
> @MrSirMacke Yes, that one looks good, thanks! Do you use proxy/vpn or some other non-standard setup?

No VPN or proxy.

**Comment by linqcan** [comment]
The latest version of the addon is now v5.0.1 and it supports Kodi >=v17.

I cannot reproduce this locally using Windows 10 and Kodi 18.4.

Following those requirements, are you @MrSirMacke still having the issues you reported then?
There have been some code changes so I am curious if those solved anything for you.

**Comment by linqcan** [comment]
Also tried with LibreElec 9.0.2 (LibreELEC-Generic.x86_64-9.0.2) and can't reproduce this issue.
