### ISSUE TITLE
Start playing a channel via jsonrpc ("method":"Addons.ExecuteAddon")

### ISSUE THREAD

**Issue by 1337v411** [kodi-svtplay/xbmc-svtplay#231]
Would it be possible to implement an interface to jsonrpc to be able to start (and stop) playing a channel (ie. SVT1).

I would love if I could automate start playing SVT1, in conjunction with script.json-cec I would be able to create my own alarm clock (waking up to "Morgonstudion" is a soft start every weekday)

Like for instance:
```
params":{"addonid":"plugin.video.svtplay","params":{"command":"getActiveChannels"}}
params":{"addonid":"plugin.video.svtplay","params":{"command":"play", "channel":"SVT1"}}
params":{"addonid":"plugin.video.svtplay","params":{"command":"stop"}}
```

**Comment by linqcan** [comment]
This is not something I am planning to add.

However, feel free to submit a pull request with the feature and we can discuss it there!
