### ISSUE TITLE
Most of the streams have NO audio inside (version 4.1.0)

### ISSUE THREAD

**Issue by Sangean99** [kodi-svtplay/xbmc-svtplay#232]
# Problem description
Most of the streams have NO audio inside (version 4.1.0)
# Steps to reproduce

# System information
Kodi version: 

Platform: Windows and Android 

Plugin version: 4.1.0

# Log

**Comment by linqcan** [comment]
Closed since there are no steps how to reproduce and I cannot reproduce it. Tested some shows from popular and they all have audio.
