### ISSUE TITLE
No audio in some items

### ISSUE THREAD

**Issue by Sangean99** [kodi-svtplay/xbmc-svtplay#235]
# Problem description
No audio in some items.
# Steps to reproduce
Open the "Popular" directory
Choose "Al Pitcher - Sverige Syndrome"
There is NO audio stream in the program
See the following screenshots in http://w3.hdsnet.hu/pmakrai/kodi/
- no_audio_stream_1.jpg
- no_audio_stream_2.jpg

Meanwhile the audio works in the following program:
Open the "Popular" directory
Choose "Pippi Långstrump"
There is audio stream in the program
See the following screenshots in http://w3.hdsnet.hu/pmakrai/kodi/
- yes_audio_stream_1.jpg
- yes_audio_stream_2.jpg

I am outside of Sweden, but these programs are not GeoIP restricted.

There is no problem with audio stream if Al Pitcher - Sverige Syndrome is opened in a browser at https://www.svtplay.se/

-->

# System information
The situation is the same with 3 different Kodis in 3 different Operation Systems.

Kodi version: 16.1 Git: 20160424-c327c53
Platform: Windows 10 Pro 1809 build: 17763.529
Plugin version: 4.1.0

Kodi version: SPMC 16.7-04 Git: 2018-02-94d913d-dirty
Platform: Android 9 (Pie)
Plugin version: 4.1.0

Kodi version: CEMC 16.1-3
Platform: Android 4.4 (KitKat)
Plugin version: 4.1.0

# Log
http://w3.hdsnet.hu/pmakrai/kodi/kodi.log
Both programs were started during the log collection!

**Comment by rs443** [comment]
I have this issue too. It seems to have started a few months ago.  About one third of all episodes have audio track missing.

**Comment by dobbelina** [comment]
This addon haven't been updated in a very long time.
Use retrospect instead if you want a working SVT play.
A hint to the developer is to use the InputStream Adaptive addon, as this is the solution
retrospect uses.

**Comment by linqcan** [comment]
Thanks for reporting this. I will verify this bug during the Python3 migration.

**Comment by linqcan** [comment]
@dobbelina Yes, this is a Kodi issue as their decoders don't handle HLS that well (old ffmpeg version).

I'm hoping that Kodi 19 will bring in some much needed updates for the core player so that this addon doesn't need other addon dependencies.

**Comment by linqcan** [comment]
Using v5.0.1 of the plugin and Kodi 18.4 I can not reproduce this.

If you can reproduce this today, drop a note here please. Thanks!
