### ISSUE TITLE
No error msg when trying to use SVTplay outside of Sweden

### ISSUE THREAD

**Issue by tomodachi** [kodi-svtplay/xbmc-svtplay#238]
# Problem description
When outside Sweden ,  trying to play content doesn't give any feedback
that its unavailable

# Steps to reproduce
go into svtplay , play content
after a couple of seconds 
you are returned back to the browse selection screen without any message
if you are on vpn (or in sweden)  the content starts playing ofc

# System information
Kodi version:  kodi 2:18.2-1~stretch all
18.2 Git:20190428-a94ccc8ba5

Platform: Linux, raspberry pi1 ,  rasbian stretch (debian 9)
Plugin version: nitzen 4.1.0

**Comment by linqcan** [comment]
As the main audience of this addon is in Sweden the reverse exists as a "fix" for your issue:

In the Addon's settings there is a setting to hide items that are restricted to Sweden. By enabling this you would not stumble upon the issue you are reporting.

Though, I know the setting is not working 100% in the current release but I have fixed that for the next release.

Hope this helps.
