### ISSUE TITLE
many streams from the svtplay don't work at all

### ISSUE THREAD

**Issue by camilla3** [kodi-svtplay/xbmc-svtplay#240]
# Problem description

* Open the "Categories" directory
* Choose "Underhållning - Öppet arkiv"
* Choose for example "Gäst hos Hagge"
*Choose for example "Magnus och Brasse"
* The stream is not playing
the same problem are for all streams and not just in "Categories" directory the live channels do work at least.

Libreelec Milhouse builds 0916 on Intel Nuc
-->

# System information
Kodi version: 

Platform: 

Plugin version: 

# Log

**Comment by linqcan** [comment]
Thank you for taking time reporting this issue.

I am unable to reproduce the issue you are experiencing. I am using Windows 10 and a official Kodi 18.4 installation.

You are using a 3rd party installation which could have its own issues.

However, if you could do the following I can try and see if I can find the issue:
* Make sure you are running the latest version of the SVTPlay addon (v5.0.1)
* Capture a log while performing the steps you reported. More info about logs here: https://kodi.wiki/view/Log_file/Easy (upload to https://paste.kodi.tv)

Thanks!

**Comment by camilla3** [comment]
I'm already using the latest svtplay addon. A question what do you mean by that im using a 3rd party installation?

**Comment by linqcan** [comment]
LibreElec builds Kodi into their own software. From what I can tell you are using a "test build"[1] of LibreElec, there could be issues with this build. Stable builds of LibreElec seems to be found here: https://libreelec.tv/downloads_new/

But if you could capture a log I could have a look if there is something wrong with the addon.

[1] https://forum.kodi.tv/showthread.php?tid=298462

**Comment by camilla3** [comment]
sorry but a Milhouse build is the newer version of what libreelec then will be

**Comment by camilla3** [comment]
oh I forgot to say, that milhouse builds are libreelec 19

**Comment by linqcan** [comment]
FWIW I have now tried to reproduce this using LibreElec 9.0.2 (LibreELEC-Generic.x86_64-9.0.2) and I can not reproduce the issue you are describing.
