### ISSUE TITLE
version 5.0.2 fail to list anything and throws exception error

### ISSUE THREAD

**Issue by ThurahT** [kodi-svtplay/xbmc-svtplay#243]
[kodi-svtplay-502-error.txt](https://github.com/nilzen/xbmc-svtplay/files/3639136/kodi-svtplay-502-error.txt)

5.0.1 works.

TIA, and for a great plugin

**Comment by linqcan** [comment]
Thank you for reporting this issue!

This is indeed an issue in the addon and it will be fixed asap.

**Comment by linqcan** [comment]
v5.0.3 will contain a fix for this and I have submitted it to Kodi. It will be pushed out when they accept the change.

Relevant PR: https://github.com/xbmc/repo-plugins/pull/2531

**Comment by ThurahT** [comment]
Thank you for carrying stable and old stable releases. We are a few left behind in our distros.
