### ISSUE TITLE
Version 5.0.4: Nothing listed and 404 when requesting API URL

### ISSUE THREAD

**Issue by f03el** [kodi-svtplay/xbmc-svtplay#245]
# Problem description
There is no content listed, and an exception is shown in the log. I'm not sure if it's related, but the request to https://www.svtplay.se/api/clusters fails with code 404.

# Steps to reproduce
* Start the SVT Play addon
* Try to list categories

I only got this reported to me, and I'm not in front of the system myself, but could use SSH to get logs etc.

# System information
Kodi version: 17.6 Git:a9a7a20

Platform: LibreElec 8.2.5 on Linux ARM 32-bit

Plugin version: 5.0.4

# Log
https://paste.ubuntu.com/p/ZQC4xdF4Mm/

**Comment by nonbinary** [comment]
Same issue.
Kodi version: 17.6 Debian package version: 2:17.6+dfsg1-4ubuntu2
Platform: PopOS (Ubuntu derivative)
Plugin version: 5.0.4

A lot of the menu options don't work: categories, and the series' individual windows (episode picker). I found two that works: searching, and listing the latest episodes.

I ran some unit tests, and the results look interesting to me:
[https://paste.ubuntu.com/p/2y2Qyg9385/](https://paste.ubuntu.com/p/2y2Qyg9385/)

I also has logs:
[https://paste.ubuntu.com/p/4hcCqCpwGz/](https://paste.ubuntu.com/p/4hcCqCpwGz/)

**Comment by nonbinary** [comment]
I actually tried downgrading to 5.0.3, but the problems are the same. Did SVT change their API?

**Comment by linqcan** [comment]
@nonbinary @f03el Thanks for reporting this!

This is indeed a change in the SVTPlay backend. The legacy API is being shutdown, I was hoping it would not. 😞

Unfortunately the new API requires a fair bit of work from my side and I will have a fix earliest next week.

**Comment by f03el** [comment]
@linqcan Thanks for maintaining this plugin! It's used a lot and very appreciated by my parents. :)

**Comment by linqcan** [comment]
> @linqcan Thanks for maintaining this plugin! It's used a lot and very appreciated by my parents. :)

Glad to hear! 😊

**Comment by nonbinary** [comment]
It's also greatly appreciated by my kids! So sad I didn't get to test the new kids mode... I should probably try to learn more kodi development so I can help out with this...

**Comment by rozahp** [comment]
I was trying to find out what had changed, and I was surprised SVT closed the api. And the new search api is quit messy. To search for shows you have to provide a few arguments, an example below.

`https://api.svt.se/contento/graphql?variables={"querystring":"blablabla"}&extensions={"persistedQuery":{"version":1,"sha256Hash":"bed799b6f3105046779adff02a29028c1847782da4b171e9fe1bcc48622a342d"}}`

Well, thanks a bunch for maintaining this plugin. We really appreciate it! Tell us if you need any help, testing or other stuff.

**Comment by linqcan** [comment]
@nonbinary Thank you!

@rozahp Thanks for looking into this. Yes, they are using GraphQL now. Their web app I mainly React now using Apollo and GraphQL. I was hoping I wouldn't have to use GraphQL. I will do some more research before deciding on an approach.

**Comment by linqcan** [comment]
Working on this now.

**Comment by linqcan** [comment]
Good progress but a lot to change. Hold on!

**Comment by linqcan** [comment]
Submitted version 5.1.0 to Kodi now that should get you going again. It is pending their approval

There are some outstanding issues noted in #246 and #247 and I will neeed to revise/refactor the code some.

https://github.com/xbmc/repo-plugins/pull/2589

**Comment by linqcan** [comment]
5.1.0 has been approved and will roll out shortly. Closing this issue now. Please open new tickets for issues on 5.1.0
