### ISSUE TITLE
No stream articles visible in Programs A-Ö

### ISSUE THREAD

**Issue by hedgoli** [kodi-svtplay/xbmc-svtplay#248]
# Problem description

There are no stream articles visible when viewed under "Programs A-Ö" or "Latest news broadcast". Channels work fine, and streams are still visible under "Latest broadcasts". 
# Steps to reproduce

* Open "Latest news broadcast 
* There are no streams available 

Alternatively 
* Open "Programs A-Ö" 
* Open any show, e.g. "Vetenskapens Värld"
* There is no content, only "Clips" folder

# System information
Kodi version:  18.4

Platform:  OSMC (Vero4k, 2019.10-1) 

Plugin version:  5.0.4

# Log

**Comment by linqcan** [comment]
Thanks for reporting this.
This is the same as #245 and a fix will roll out shortly.
