### ISSUE TITLE
URL for "Byggare Bob" seems to be incorrect

### ISSUE THREAD

**Issue by kristoffern** [kodi-svtplay/xbmc-svtplay#25]
Navigating to "Categories/Barn/Byggare Bob" and starting one of the episodes (top 4 tested) fails.
See log output below.
However "Categories/Barn/Bondgården" for example works just fine.

Comparing the URL:s thats being called, there is a slight difference as "Byggare Bob" contains "secure" as part of the URL (might be irrelevant)

http://svtplay7b-f.akamaihd.net/i/20120924/198967/JOHANS_BONDGARD-014A-mp4-,c,e,d,b,-v1-e2172dc4f2e9b408.mp4.csmil/master.m3u8 [WORKS]

http://svtplay10r-f.akamaihd.net/i/se/secure/20121007/1151547-014A/BOB_THE_BUILDER-014A-dad8aafd7288375c_,900,320,420,620,1660,2760,.mp4.csmil/master.m3u8 [FAILS]

Trying to open these URL:s in Windows/VLCPlayer produces the same behaviour:
"Bondgården" works, and "Byggare Bob fails.

[OUTPUT xbmc.log]

20:38:28 T:6036  NOTICE: -->Python Interpreter Initialized<--
20:38:29 T:6036  NOTICE: CommonFunctions-1.2.0
20:38:33 T:4340  NOTICE: DVDPlayer: Opening: http://svtplay10r-f.akamaihd.net/i/se/secure/20121007/1151547-014A/BOB_THE_BUILDER-014A-dad8aafd7288375c_,900,320,420,620,1660,2760,.mp4.csmil/master.m3u8
20:38:33 T:4340 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:38:33 T:5024  NOTICE: Creating InputStream
20:38:33 T:6036   ERROR:  XFILE::CPluginDirectory::EndOfDirectory - called with an invalid handle.
20:38:34 T:5024  NOTICE: Creating Demuxer
20:38:40 T:5024   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file http://svtplay10r-f.akamaihd.net/i/se/secure/20121007/1151547-014A/BOB_THE_BUILDER-014A-dad8aafd7288375c_,900,320,420,620,1660,2760,.mp4.csmil/master.m3u8
20:38:40 T:5024   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
20:38:40 T:5024  NOTICE: CDVDPlayer::OnExit()
20:38:40 T:5024  NOTICE: CDVDPlayer::OnExit() deleting input stream
20:38:40 T:4340   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.svtplay/?url=%2Fvideo%2F150839%3Ftype%3Dembed&mode=video]
20:38:40 T:4340  NOTICE: CDVDPlayer::CloseFile()
20:38:40 T:4340 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:38:40 T:4340  NOTICE: DVDPlayer: waiting for threads to exit
20:38:40 T:4340  NOTICE: DVDPlayer: finished waiting

**Comment by nilzen** [comment]
If you try the same url again does it still fail? Seems like it fails some times and works if you retry, it's nothing we can do in the addon to fix it if thats the case.

**Comment by kristoffern** [comment]
For me and on my setup it fails every time (tried ~10 times now)
The same goes when I open the parsed URL mentioned in previous comment on another Windows computer/VLC Player.
My setup/HTPC:
Windows 7
XBMC 11.0 (official March release)
Latest SVT Play commit: 4a742b31fe7b3e08d0b9d49fc73073a21120ab54)

**Comment by nilzen** [comment]
Oh March release... That's way to old to handle HLS (Http Live Streaming) it has only been in XBMC master for around 2 months.

**Comment by kristoffern** [comment]
Thanks, I'll update XBMC and update the issue accordingly.

**Comment by kristoffern** [comment]
Works just fine on Nightly build 20121015.
Closing issue, sorry for the false alert...
