### ISSUE TITLE
watched status isnt working

### ISSUE THREAD

**Issue by sopparus** [kodi-svtplay/xbmc-svtplay#261]
# Problem description
watched status isnt displayed or saved correctly

# Steps to reproduce
mark an episiod watched, and check list

# System information
Kodi version: 
18.6

Platform: 
windows

Plugin version: 
5.1.9

# Log

**Comment by linqcan** [comment]
Thanks for reporting this!

I have intentionally disabled this for some reason that I have forgotten. Sorry!

I will think about this and get back to you with an answer as soon as I can.

**Comment by linqcan** [comment]
Can't find a good reason for disabling watched status, I will revert the changes to the addon and release a fix the coming days.

**Comment by sopparus** [comment]
thanks!

**Comment by linqcan** [comment]
v5.1.10 has been submitted to Kodi pedning their approval.
