### ISSUE TITLE
Add support for Kodi 19 Matrix (Python 3)

### ISSUE THREAD

**Issue by rikardfries** [kodi-svtplay/xbmc-svtplay#263]
# Problem description
It does not work in Matrix Alpha 1 since it is not using python 3..

# Steps to reproduce
it is just disabled.

# System information
Kodi version: 
Matrix
Platform: 
Windows
Plugin version: 
5.1.8
# Log

**Comment by linqcan** [comment]
Thanks for reporting this! 

Looks like matrix needs a separate build after all.. 😕 

The addon is P3 compatible btw, just needs a new build for matrix.

**Comment by rikardfries** [comment]
It might be as easy as changing the demands for python to 3 and it will work. If you wish me to test it, just send a link.

**Comment by linqcan** [comment]
In best case it is enough to change python version to 3.0.0 in addon.xml and the addon version to something higher than what you have. Worst case they have made more changes since the pre-release. You can try that out if you need it working asap. 

I need to do more work nd thinking around this however as I don't want to maintain two branches. It will be done before matrix stable but has no other time frame.

**Comment by rikardfries** [comment]
I will try to cheat a bit tomorrow and see what happens.  Thanks for answering me.

**Comment by rikardfries** [comment]
> In best case it is enough to change python version to 3.0.0 in addon.xml and the addon version to something higher than what you have. Worst case they have made more changes since the pre-release. You can try that out if you need it working asap.
> 
> I need to do more work nd thinking around this however as I don't want to maintain two branches. It will be done before matrix stable but has no other time frame.

_**Worked like a charm. Happy! Thank you!**_

**Comment by linqcan** [comment]
Note to self: 

https://forum.kodi.tv/showthread.php?tid=351745
https://github.com/xbmc/kodi-addon-submitter

**Comment by linqcan** [comment]
V5.1.12 is now available in the matrix addon repo.

**Comment by rikardfries** [comment]
Perfect, thank you. Seems to work fine.
