### ISSUE TITLE
Subtitles missing

### ISSUE THREAD

**Issue by 2019-05-10** [kodi-svtplay/xbmc-svtplay#266]
# Problem description

While watching programs, subtitles are not displayed.
In settings, subtitles are enabled.
Checking the subtitle settings (player toolbar, subtitle icon), the dialog says "None".
Watching the same programs in a browser, subtitles are displayed.
Watching the same programs via KODI addon "retrospect", subtitles are displayed.

_After_ watching a program via KODI addon "retrospect" (which has subtitles), svtplay suddenly has subtitles as well.

Looks like svtplay fails to download subtitles for some reason, but finds them once downloaded.

# Steps to reproduce

* Open the "Categories" directory
* Choose "Humor"
* Choose "Svenska Nyheter"
* The stream plays, but without subtitles

# System information
Kodi version: 
18.9.0 Git:leia_pi4_18.9-Leia
Platform: 
LibreELEC 9.2.6
Plugin version: 
5.1.12
# Log

**Comment by linqcan** [comment]
Hi!
Do you still have issues with this?
I tried with Kodi 19 and 18.9 on WIndows and "Avsnitt 6" of "Svenska Nyheter" shows subtitles when I toggle them on. I.e I can not reproduce the issue you are reporting.

**Comment by linqcan** [comment]
No response and could not reproduce. Closing.
