### ISSUE TITLE
Browsing is broken, log shows KeyError issue

### ISSUE THREAD

**Issue by martinpub** [kodi-svtplay/xbmc-svtplay#267]
# Problem description
When trying to browse anything, e.g. a category, a show, etc., an error is thrown and the action is unsuccessful. No way to get to playback. The log shows a KeyError problem, not sure what that is, if it's related to API changes or something else.

# Steps to reproduce
* Open the "Popular" directory, or any other directory
* Kodi gives general error and more info is in the log
* Streams are unreachable

# System information
Kodi version: 19.4.0

Platform: OSMC 2022.03-1

Plugin version: 5.1.12

# Log
https://pastebin.ubuntu.com/p/DDKc9FN4P4/

**Comment by linqcan** [comment]
Hi!
Thanks for reporting this! 🙏 
I can confirm it is broken (Kodi 19.3 Windows).

Note to future me: Github had turned of the cron run of the test suite due to repo inactivity...

**Comment by linqcan** [comment]
Backend has changed a bit, working on adapting to it. No ETA for fix.

**Comment by ToddeSwe** [comment]
Hi

I can confirm this as well, here's my error clip:

2022-04-04 22:34:29.856 T:25960   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'data'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.svtplay\default.py", line 12, in <module>
                                                       svt_play.run(PLUGIN_PARAMS)
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.svtplay\resources\lib\svtplay.py", line 74, in run
                                                       self.navigate(arg_mode, arg_id, arg_params)
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.svtplay\resources\lib\svtplay.py", line 112, in navigate
                                                       self.view_channels()
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.svtplay\resources\lib\svtplay.py", line 179, in view_channels
                                                       channels = self.graphql.getChannels()
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.svtplay\resources\lib\api\graphql.py", line 215, in getChannels
                                                       json_data = self.__get(operation_name, query_hash)
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.svtplay\resources\lib\api\graphql.py", line 362, in __get
                                                       return json_data["data"]
                                                   KeyError: 'data'
                                                   -->End of Python script error report<--

Hope this will be a small easy thing to fix. :)

**Comment by martinpub** [comment]
> Backend has changed a bit, working on adapting to it. No ETA for fix.

Thanks!

**Comment by linqcan** [comment]
Fixed in code, working on getting the submission to Kodi to work.

**Comment by linqcan** [comment]
Submitter issue for reference: https://github.com/xbmc/kodi-addon-submitter/issues/24

**Comment by ToddeSwe** [comment]
Nu fungerar kanaler, program och kategori.

**Comment by linqcan** [comment]
> Nu fungerar kanaler, program och kategori.

What? Are you using v5.1.12 or have created your own version from the source code?

**Comment by ToddeSwe** [comment]
> > Nu fungerar kanaler, program och kategori.
> 
> What? Are you using v5.1.12 or have created your own version from the source code?

I’m using v5.1.12.

**Comment by linqcan** [comment]
> > > Nu fungerar kanaler, program och kategori.
> > 
> > 
> > What? Are you using v5.1.12 or have created your own version from the source code?
> 
> I’m using v5.1.12.

That's mind boggling as svt removed stuff in the backend. They must have reverted that change then... 🙄 Either way v5.1.13 is aligned with their current backend better so it's a good change to make.

**Comment by ToddeSwe** [comment]
> > > > Nu fungerar kanaler, program och kategori.
> > > 
> > > 
> > > What? Are you using v5.1.12 or have created your own version from the source code?
> > 
> > 
> > I’m using v5.1.12.
> 
> That's mind boggling as svt removed stuff in the backend. They must have reverted that change then... 🙄 Either way v5.1.13 is aligned with their current backend better so it's a good change to make.

Yes it is. Is this new version available for download already?

**Comment by martinpub** [comment]
I can confirm that Channels, Programs A-Z directories are functional now, still on 5.1.12. However, Popular, Latest programs directories are still not working.

**Comment by linqcan** [comment]
> > > > > Nu fungerar kanaler, program och kategori.
> > > > 
> > > > 
> > > > What? Are you using v5.1.12 or have created your own version from the source code?
> > > 
> > > 
> > > I’m using v5.1.12.
> > 
> > 
> > That's mind boggling as svt removed stuff in the backend. They must have reverted that change then... 🙄 Either way v5.1.13 is aligned with their current backend better so it's a good change to make.
> 
> Yes it is. Is this new version available for download already?

No, there is a bug in the submission pipeline that I am waiting for Kodi to fix before I can submit the new version.

**Comment by linqcan** [comment]
> I can confirm that Channels, Programs A-Z directories are functional now, still on 5.1.12. However, Popular, Latest programs directories are still not working.

That makes more sense 😅 Thanks!

**Comment by linqcan** [comment]
V5.1.13 should now be available. Fanart is missing due to not being available in the api anymore, see separate issue if you want to chime in.

**Comment by ToddeSwe** [comment]
> V5.1.13 should now be available. Fanart is missing due to not being available in the api anymore, see separate issue if you want to chime in.

All sections are working fine now in the new version. Thank so much.

**Comment by martinpub** [comment]
> V5.1.13 should now be available. Fanart is missing due to not being available in the api anymore, see separate issue if you want to chime in.

Thank you very much for the fix!
