### ISSUE TITLE
Thumbnail issue

### ISSUE THREAD

**Issue by dobbelina** [kodi-svtplay/xbmc-svtplay#269]
# Problem description
After the latest update thumbnails disappeared on my Confluence skin
with "Media View".
If it could be fixed it would be great, screenshot below.
Thanks for this great addon!

# System information
Kodi version: 
Kodi 18.9 & 19.4
Platform: 
Windows
Plugin version: 
5.1.13
# Screenshot
<img width="480" alt="screenshot000" src="https://user-images.githubusercontent.com/46063764/162135029-104e7d55-d54d-4017-b731-52e123d15139.png">

**Comment by linqcan** [comment]
Yeah, those are called fanart and were previously set to an episode"s show (parent). That information is not available anymore unfortunately for latest, last chance, popular etc. Hence it is not showing any picture in side theme mode.

What we could do is duplicate the episode thumbnail into the fanart, that would make some views look weird but this one would look OK I think.

You can decide, should we duplicate the episode thumbnail as fanart? 😊

**Comment by dobbelina** [comment]
Hi @linqcan 

Yes, that sounds like a good idea, there's no fanart available anyway.

**Comment by linqcan** [comment]
Cool! I'll update here when the change is ready 😊

**Comment by linqcan** [comment]
v5.1.14 contains at fix for this and should be available in Kodi very soon.
