### ISSUE TITLE
Unable to open item folders without positionInSeason key

### ISSUE THREAD

**Issue by pederalm** [kodi-svtplay/xbmc-svtplay#271]
# Problem description
I'm unable to open some item folders.

# Steps to reproduce
* Open the "Categories" directory
* Choose "Barn"
* Choose "Pinsamheter"
* The stream is not playing

# System information
Kodi version: 19.4

Platform: Windows

Plugin version: 5.1.14+matrix.1

# Log
key error for "positionInSeason "

The item folder "Pinsamheter" doesn't include the item key positionInSeason. Changing row 117 in getVideoContent() from 
`if content["type"] == "Season" and content["name"] and item["positionInSeason"]:`
to:
`if content["type"] == "Season" and "name" in content and "positionInSeason" in item:`
solved this issue

**Comment by linqcan** [comment]
Thank you for reporting this!

**Comment by linqcan** [comment]
v5.1.15 should have a fix for this.
