### ISSUE TITLE
Unexpected autoplay last episode in Populärt 

### ISSUE THREAD

**Issue by pederalm** [kodi-svtplay/xbmc-svtplay#284]
If the user selects an item in Populärt that is a folder with multiple episodes the plugin autoplay the latest episode. Expected behavior should be just to list all episodes. 

The items in Populärt has been changed by SVT. It does no longer contains single popular episodes.

# System information
Kodi version: 19.4
Platform: Linux Bullseye
Plugin version: 5.1.17+matrix.1

**Comment by linqcan** [comment]
Thanks for reporting this!

**Comment by linqcan** [comment]
@pederalm I have looked that this now and I am not sure I agree, or maybe I don't understand and you can help me.

When I am looking at the web app (svtplay.se) and compare with this addon they behave similar. The web app shows the latest item as a pop-over when you click an item (new behavior, it played them before), The addon plays the same item automatically.

The only odd/new behavior I found was that there is a menu item called "SVT Nyheter" that, when clicked, causes a crash in addon.
- [ ] Look into and fix crash related to SVT Nyheter in Populärt

@pederalm can you give me examples of items that are behaving different from before? Thanks!

**Comment by pederalm** [comment]
@linqcan SVT has changed the content of the directory Populärt. It no longer contains the most popular episodes but the most popular shows (some films are also in the list right now, e.g. "Patrik 1,5"). Each show in the list is a directory and my expectation is that I should enter that directory on selection, not autoplay the latest episode. I compare the behavior with the SVT-app on Android. For episodes/films in the list, autoplay is the expected behavior I think.

If we compare with the web app you have the option in the pop-over to play the latest episode (play button) but also to click on the link "Mer om programmet". When you click on that link you just enter the directory of the show, just as in the Android app (that don't have the play button).

My wish is that you change the behavior to enter the directory instead of playing the latest episode when selection a show.

**Comment by linqcan** [comment]
@pederalm Thanks for elaborating this for me. I see what you mean and how it is inconsistent with both the official apps, but also based on what information is shown in Kodi (specifically that descriptions describe the program in general and not an episode but a certain episode starts when the user clicks on that menu item). 

I will look into this, though don't expect any swift solutions 😅
