### ISSUE TITLE
Addon needs update, new Api since 4/9

### ISSUE THREAD

**Issue by dobbelina** [kodi-svtplay/xbmc-svtplay#286]
# Problem description
Addon måste fixas, nytt api sen 4/9

# Steps to reproduce

# System information
Kodi version: 

Platform: 

Plugin version: 

# Log

**Comment by linqcan** [comment]
Thanks for reporting this!

The regression tests have identified a change too but I will hold on a day to see if this is lasting changes or not. Historically there have been shorter times of regression before it goes back to working again.

**Comment by springjools** [comment]
Samma, måste vara nånting som ändrats i apin:

`
[plugin.video.svtplay] Missing key 'data' in JSON response: {'errors': [{'message': 'PersistedQueryNotFound'}]} for operationName=AllGenres, variables={}, queryHash=6bef51146d05b427fba78f326453127f7601188e46038c9a5c7b9c2649d4719c
2023-09-04 22:30:45.823 T:2348560   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not iterable
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.svtplay/default.py", line 12, in <module>
                                                       svt_play.run(PLUGIN_PARAMS)
                                                     File "/home/pi/.kodi/addons/plugin.video.svtplay/resources/lib/svtplay.py", line 68, in run
                                                       self.navigate(arg_mode, arg_id, arg_params)
                                                     File "/home/pi/.kodi/addons/plugin.video.svtplay/resources/lib/svtplay.py", line 91, in navigate
                                                       self.view_categories()
                                                     File "/home/pi/.kodi/addons/plugin.video.svtplay/resources/lib/svtplay.py", line 147, in view_categories
                                                       for category in categories:
                                                   TypeError: 'NoneType' object is not iterable
                                                   -->End of Python script error report<--
`

**Comment by springjools** [comment]
Det enda som funkar är live-kanalerna

**Comment by linqcan** [comment]
Thanks for reporting. Here are the automatic regression tests I referred to earlier. They run everyday to discover changes.
https://github.com/kodi-svtplay/xbmc-svtplay/actions/workflows/python-package.yml

**Comment by andreas1974** [comment]
Here is a thread about SVTPlay on Retrospect, which also stopped working. I have not tried to update it yet, but perhaps it can be of help for you: https://github.com/retrospect-addon/plugin.video.retrospect/issues/1718

I noticed that SVT introduced an option to log on to an account using Google or email/password, at about the same time as the programs stopped showing up in the lists of the Nilzen Kodi-xbmc-SVTPlay plugin. 

By the way, it would be splendid if the login possibility was added to this plugin too, with the addition of the "Min lista" list, for favourites. Then I could add favourites to watch from my computer during daytime, and in the evening I could enter Min lista on the Raspberri/Kodi connected to my tv.

I'm so glad this plugin has been working on my Raspberry 2, so I hope you won't require a newer Raspberry version when making the new version... please!

**Comment by linqcan** [comment]
Thanks all for highlighting the issues! 
Unfortunately I don't bandwidth to fix this right away but I hope to be able sooner rather than later.

**Comment by springjools** [comment]
That's totally understandable. Is what you need basically a new regex with how to process the streams from the new api?

**Comment by linqcan** [comment]
> That's totally understandable. Is what you need basically a new regex with how to process the streams from the new api?

No, that's not how it works. It's more of a mapping thing and in this case I saw they have done some bigger structural changes that I need to consider and rewrite for as well.

**Comment by tomoqv** [comment]
Yes, also waiting for a fix for this.

**Comment by linqcan** [comment]
I have submitted v5.1.19 to Kodi with the needed changes. It might take some time before they merge it.

If you can't wait, and know your way around manually installing addons, you can dowload v5.1.19 from the [Releases](https://github.com/kodi-svtplay/xbmc-svtplay/releases)

**Comment by basrieter** [comment]
Merged them in the https://github.com/xbmc/repo-plugins

**Comment by linqcan** [comment]
> Merged them in the https://github.com/xbmc/repo-plugins

Thanks for the swift merge @basrieter! 🙏

**Comment by andreas1974** [comment]
It's great that you managed to make the update, thank you @linqcan!

But I'm not sure what "merging into retro-plugins" should mean for me as an end-user.
I got no auto-update of the plugin, and when selecting to update there is no new version (just 5.1.18). Is there still something that remains to be done?

I've got LibreLEC 9.2.8 "Just enough OS for Kodi". RPi2.arm. Running Kodi "Leia" 18.9, which is the latest one supported on the Raspberry 2.

**Comment by linqcan** [comment]
> It's great that you managed to make the update, thank you @linqcan!
> 
> But I'm not sure what "merging into retro-plugins" should mean for me as an end-user. I got no auto-update of the plugin, and when selecting to update there is no new version (just 5.1.18). Is there still something that remains to be done?
> 
> I've got LibreLEC 9.2.8 "Just enough OS for Kodi". RPi2.arm. Running Kodi "Leia" 18.9, which is the latest one supported on the Raspberry 2.

You don't need to anything, Kodi auto updates all add-ons when the changes have been accepted ("merged"). They are accepted now and the update will roll out soon.

**Comment by andreas1974** [comment]
Great! I got the update around 21:45 yesterday evening, and it works! Thanks again!

**Comment by linqcan** [comment]
> Great! I got the update around 21:45 yesterday evening, and it works! Thanks again!
> 
> However there is a slight problem with the names in the lists, and in the information. It seems the main titles are missing, so for many programs it just says "avsnitt 2" and the main title "Fröken Friman" is not present.
> 
> There are also a lot of shorter clips that perhaps have no main title on SVT either, and for them the descriptions in the Kodi lists perhaps work well ... Like this one: https://www.svt.se/nyheter/utrikes/unikt-fynd-i-okengrotta-fyra-romerska-svard had a name in Kodi about 1000 år gamla svärd ... I don't know what main title they ought to be for clips like that, perhaps there is one.

Please file a new issue for this. Thank you!

**Comment by tomoqv** [comment]
I am on LibreElec 19.5-Matrix. The latest SVTPlay in the repos is 5.1.17. Tried to install from zip, but get unmet python 2 depencies.

**Comment by linqcan** [comment]
> I am on LibreElec 19.5-Matrix. The latest SVTPlay in the repos is 5.1.17. Tried to install from zip, but get unmet python 2 depencies.

@tomoqv strange that it hasn't showed up. Try this zip
https://mirrors.kodi.tv/addons/matrix/plugin.video.svtplay/plugin.video.svtplay-5.1.19+matrix.1.zip

**Comment by linqcan** [comment]
@tomoqv i am not sure librelec using the official addon repository. You should probably check with them.

**Comment by tomoqv** [comment]
> Try this zip
> https://mirrors.kodi.tv/addons/matrix/plugin.video.svtplay/plugin.video.svtplay-5.1.19+matrix.1.zip

Thanks, that zip worked fine!

**Comment by andreas1974** [comment]
> I am on LibreElec 19.5-Matrix. The latest SVTPlay in the repos is 5.1.17. Tried to install from zip, but get unmet python 2 depencies.

I've got the previous OS version (Leia) also running on LibreElec, and the new version was automatically installed along with a number of dependencies yesterday evening.
I just wanted to add this information. (I notice that you got it to work from the zip.)
