### ISSUE TITLE
Starting a program from the favorites menu has odd effects on "resume" and "information"

### ISSUE THREAD

**Issue by andreas1974** [kodi-svtplay/xbmc-svtplay#289]
# Problem description
Starting a program from the Favourites menu results in missing information and resume does not work (the program starts from 00:00 even after selecting to resume at "20:35" (the question to resume shows up).
# Steps to reproduce

* Start a program (**not** from the favourites menu) and watch a while (fast forward a few minutes) to get a resume point for later watching. [image1]
* Press the (i) to view information. (Information shows up correctly.) [image2]
* Add the same program as a favourite.
* Start the program from the favourites menu. [image3]
* You will get a question whether to resume at xx:xx. **Chose to resume. (The show will nevertheless start at 00:00).**
* Press the (i) to view information. (The information is "not available".) [image4]

[image1]
![DSCF6420](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/d5ebd0a0-0ef2-4725-a624-f90936bc975a)

[image2]
![DSCF6422](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/dd6f4e73-2e25-4b05-9f0a-b7d286a795f1)

[image3]
![DSCF6423](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/5eec8940-dd39-44ef-82b9-64952add39e7)

[image4]
![DSCF6421](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/bc032965-4a4c-4124-8ac0-80077c852432)

# System information
Kodi version: 18.9

Platform: LibreElec 9.2.8

Plugin version: 5.1.20

# Log

**Comment by linqcan** [comment]
Thanks for reporting!

Will look into this, though it will have to wait a bit.

**Comment by dobbelina** [comment]
I miss the description on "Senaste/Latest programs" as can be seen below:
![image](https://github.com/kodi-svtplay/xbmc-svtplay/assets/46063764/4657a064-f6a4-4a8a-8c2c-96c1cb8fe1a3)
and
![image](https://github.com/kodi-svtplay/xbmc-svtplay/assets/46063764/b41ea123-3d5f-408d-af87-d9056be95168)

**Comment by linqcan** [comment]
> I miss the description on "Senaste/Latest programs" as can be seen below: ![image](https://user-images.githubusercontent.com/46063764/268170017-4657a064-f6a4-4a8a-8c2c-96c1cb8fe1a3.png) and ![image](https://user-images.githubusercontent.com/46063764/268170073-b41ea123-3d5f-408d-af87-d9056be95168.png)

@dobbelina are you sure you are running v5.1.20?

**Comment by dobbelina** [comment]
Yes i am. kodi 20.2 Windows
![image](https://github.com/kodi-svtplay/xbmc-svtplay/assets/46063764/971cddcd-9327-4fd5-8bfc-63d235c1cfa1)

**Comment by andreas1974** [comment]
This may not be the same issue as the one I described in this thread about differences when starting a program from the Kodi favourites list.
But anyway @dobbelina is right. It's the same on my Raspberry. However, when selecting the title from a **search**, the long description is showing.
![latest DSCF6433](https://github.com/kodi-svtplay/xbmc-svtplay/assets/998258/7b8a7ed3-f9cd-48b8-8d20-b54aea721736)

**Comment by linqcan** [comment]
This is unfortunately how the API looks now for listings in sections like this one. What you are comparing with in one of the pictures is the details modal which is another API endpoint. The available information is what you see in Kodi and what can be seen in the background of your screenshot.

Regarding how it differs with search, that's because the API response is different there (you can this in the web app how listings differs between the two.) 

Historically, this is how it's always been, data available in responses come and go depending on what they need in the web app. Can't do much about that. And in this specific case I don't want to do extra API calls to get the data as that would make the browsing experience much slower.

Hope this explains what you are experiencing.

**Comment by dobbelina** [comment]
To not slow down with extra api calls for recent on all the items listed, couldn't one make the api call individually when you hit the **i**(info) button?
It would be similar as when you hoover over the program in the browser and get that terrible looking pop-up.
(SVT webpage is terrible b.t.w)
Having to go thru the hoop of doing a search to get this info is not optimal.
Not even if i go thru categories=>Filmer do i get a proper listing.

**Comment by linqcan** [comment]
> To not slow down with extra api calls for recent on all the items listed, couldn't one make the api call individually when you hit the **i** button? It would be similar as when you hoover over the program in the browser and get that terrible looking pop-up. (SVT webpage is terrible b.t.w)

Good idea though that is not possible for a Kodi addon. An addon only supply list item data to Kodi that Kodi then uses to populate the UI.

**Comment by linqcan** [comment]
@andreas1974 regarding the original issue
> Starting a program from the Favourites menu results in missing information and resume does not work (the program starts from 00:00 even after selecting to resume at "20:35" (the question to resume shows up).

I looked into this and there is nothing I can do wrt this. I don't know why Kodi can resume a stream from the listing but not from favourites. Sorry!

**Comment by andreas1974** [comment]
Were you able to repeat the error in your environment?

I note that a year ago Scott967 wrote this: The problem appears to be that plugin items that are added to favorites, and launched from the favorites dialog, don't pass resume point or other item metadata to the player. 
https://forum.kodi.tv/showthread.php?tid=369537

He also has a link to Imugr that shows a video describing the exact same behaviour: https://imgur.com/a/bamXedL

The Kodi developers may not have taken notice?

Thanks anyway for trying!

**Comment by linqcan** [comment]
Favorites is a native Kodi feature. The addon doesn't pass any data actively to Kodi for this, nor am I aware of any way of doing so. The issue you referred to seemed to speculate mostly about what could be the cause (?). I'd recommend you to post an issue in the Kodi forums as it might be a more general issue?

**Comment by andreas1974** [comment]
I'll may try that. But I'd like to know whether it's a repeatable error, that you also were able to reproduce.

**Comment by linqcan** [comment]
I can reproduce it on my Windows machine with Kodi 19

**Comment by andreas1974** [comment]
Hi again!

I sent the question to the Kodi add-ons forum. Would you have a look at https://forum.kodi.tv/showthread.php?tid=374491&pid=3166838#pid3166838  (have a look at jepsizofye  at 18:05)

I'm not sure if the ones who answer realize that the resume time is **showing up** correctly (I've pointed it out at least twice). Perhaps there is more to it.

I don't understand all of it.

Andreas

**Comment by linqcan** [comment]
@andreas1974 thanks for digging into this. I still don't understand why an addon would need to go through all the trouble they are suggesting given that resume **works** when you play the item from within the addon. To me, that's a Kodi bug. I will look at the information again at later and try to understand if there is something indeed I can do or if I should file a Kodi issue for it. Thanks again!

**Comment by andreas1974** [comment]
**[jepsizofye]** added some sample code today. (https://forum.kodi.tv/member.php?action=profile&uid=477027)
If it doesn't fully describe what's missing for "favourites resume" to work even though it works from within the plugin, I suggest you send him a question in that same thread. He seems to be a very helpful guy!

**Comment by matthuisman** [comment]
Found the issue. its a bug in Kodi I think

There is a workaround:
https://forum.kodi.tv/showthread.php?tid=374491&pid=3167591#pid3167591

**Comment by linqcan** [comment]
> Found the issue. its a bug in Kodi I think
> 
> There is a workaround: https://forum.kodi.tv/showthread.php?tid=374491&pid=3167591#pid3167591

Thanks for letting me know! 🙏
I'll might look into the Kodi bug to see if I can do something to solve it there for real.
