### ISSUE TITLE
Playback error on newer episodes of bluey on Libreelec

### ISSUE THREAD

**Issue by gandalth** [kodi-svtplay/xbmc-svtplay#294]
# Problem description
I notice a playback error. I encountered this when trying a newer episode of bluey. I double checked that the same show/episode on a browser (svtplay.se) works. Older episodes play back fine on kodi.

# Steps to reproduce
* Open the "Popular" directory
* Choose "Bluey"
* Choose one of the newer episodes marked "2025". The log below is for the episode called hinderbana.

# System information
Kodi version: 21.1

Platform: Libreelec 12.0.1, RPi5

Plugin version: 5.1.21-matrix1

# Log
2024-10-12 15:13:37.649 T:844      info <general>: VideoPlayer::OpenFile: plugin://plugin.video.svtplay/?mode=video&id=%2Fvideo%2FKrQdGzq%2Fbluey%2Fhinderbana
2024-10-12 15:13:38.211 T:977     error <general>: CCurlFile::Stat - <https://svt-vod-secure-1a.akamaized.net/d0/secure/20240930/a38f8a8d-687b-433c-b6f2-310bd9749fc9/hls-ts-
avc.m3u8> Failed: HTTP response code said error(22)
2024-10-12 15:13:38.211 T:977      info <general>: Creating InputStream
2024-10-12 15:13:38.524 T:977     error <general>: CCurlFile::CReadState::FillBuffer - (0x7ffeec0011d0) Failed: HTTP returned code 403
2024-10-12 15:13:38.524 T:977     error <general>: CCurlFile::Open - <https://svt-vod-secure-1a.akamaized.net/d0/secure/20240930/a38f8a8d-687b-433c-b6f2-310bd9749fc9/hls-ts-
avc.m3u8> Failed with code 403:

**Comment by linqcan** [comment]
Thanks for reporting this!
Happily surprised the addon has worked so long without any patches 😊

I will look into this to see if there is something that can be done.

**Comment by linqcan** [comment]
I just had a quick look. I think this might be due to the same reason some shows cannot be viewed on some smart TVs (like my Samsung): they have implemented a new DRM protection that Kodi does not support.

"Rubble and Crew" cannot be viewed on my Samsung TV, is that also not possible to view on your Kodi setup?

Source in Swedish: https://www.svt.se/kontakt/varfor-kan-jag-inte-se-vissa-program-pa-min-smart-tv

**Comment by linqcan** [comment]
Just checked a new Bluey episode on my Samsung TV, and it worked. So might not be the same issue after all...

**Comment by linqcan** [comment]
I just installed Kodi 21 (latest) on my Ubuntu machine and I cannot reproduce the issue using the episode "Skicka paketet" that has production year "2025".

"Rubble and Crew" works fine too, and this is a show which definately has new DRM protection.

Do you still have issues with playback @gandalth ?

**Comment by gandalth** [comment]
I checked all recent Bluey episodes on Wednesday and all of them didn't work.

I also noticed that kodi does not show video- and audiocodec properties (such as hevc) when selecting the episode. It does show this information for the older episodes.

I will try Rubble and Crew, but I am currently on semester. I'll provide feedback in one week.

**Comment by gandalth** [comment]
I am back from Semester and able to check again! :-)

I just checked the currently available episodes of Bluey and the playback issue still exists.
Also, I checked a few episodes of Rubble & Crew, and a few of Paw Patrol, and I get the issue on all of these.

Any ideas of further checks / log files I could provide on this topic?
Do you have any chance to check on a Raspberry Pi (or maybe another arm-based device) to reproduce the issue?

**Comment by linqcan** [comment]
I don't know of any better logs than what you've got. Given it works on an
official Kodi installation I'd take the issue to libreelec.

I only have amd64 to test on.

**Comment by gandalth** [comment]
I have now also tested on amd64 (an older Linux Mint with Kodi 19.4) and I confirm that playback works fine. Hence I changed the title of this issue.

I will open an issue with libreelec, and link back to this discussion:

https://github.com/LibreELEC/LibreELEC.tv/issues/9465

**Comment by gandalth** [comment]
Interestingly, the playback now works fine on LibreElec, though my setup hasn't changed nor LibreElec has rolled out any updates.

I'm closing the issue and apologize for the effort.
