### ISSUE TITLE
CommonFunctions dependency missing

### ISSUE THREAD

**Issue by carlba** [kodi-svtplay/xbmc-svtplay#32]
XBMC Version: Frodo

I tried to checkout the frodo branch to see if I could get it working. I have checked out the folder in the addons folder. The addon is detected by XBMC but when I try to launch it the following information is seen in the logfile.

20:28:08 T:824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named CommonFunctions
                                            Traceback (most recent call last):
                                              File "C:\test\XBMC\portable_data\addons\xbmc-svtplay\default.py", line 10, in <module>
                                                import CommonFunctions
                                            ImportError: No module named CommonFunctions
                                            -->End of Python script error report<--
20:28:08 T:824    INFO: Python script stopped

Is CommonFunctions your own dependency or is it a library / a common library for XBMC plugins?

**Comment by kokangit** [comment]
Install youtube addon, this will resolve the dependency since it also depends on CommonFunctions aka parsedom.
