### ISSUE TITLE
SVT format changed again, breaks playback...

### ISSUE THREAD

**Issue by pajen** [kodi-svtplay/xbmc-svtplay#42]
bug log:

 File "/home/...../.xbmc/addons/xbmc-svtplay-frodo/default.py", line 361, in startVideo
                                                jsonString = common.parseDOM(html, "param", attrs = { "name": "flashvars" }, ret = "value")[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by linqcan** [comment]
They haven't changed anything from what I can tell.

Which video did you try to play?
Which version of XBMC are you running?
Which version of the plugin are you running?

**Comment by nilzen** [comment]
I just noticed the same, tried playing Uppdrag granskning 12 on OSX with Beta 1...

**Comment by linqcan** [comment]
Seeing this now too, but it seems to be XBMC that is acting strange. The VIDEO_PATH prefix has been clipped to only "...?type" instead of "...?type=embed".
Looking in to it.
Strange though, worked before (right?) and SVT hasn't changed anything and we haven't merged anything new yet...

**Comment by linqcan** [comment]
Don't get it. Too tired. Will look at it tomorrow if it isn't solved when I wake up ;) 
From the logs I can see that we set the url to "...?type=embed" but after doing params.get we only get "...?type". Strange...

**Comment by linqcan** [comment]
I have fixed it now, but I honestly don't know what happened. I had to quote the URL string to get XBMC to treat it properly. Can someone tell what happened overnight that made this break?

Pull #43 fixes this issue.

When reporting issues, please enable "Debug" in SVT Play settings. Thank you.

**Comment by pajen** [comment]
here is the culprit I believe;
http://hg.tobiasussing.dk/hgweb.cgi/commonxbmc/diff/6122bb38e0d8/plugin/lib/CommonFunctions.py

since CommonFunctions nowadays happens to unquote_plus-ing the url in getParameters, the url needs an "extra quoteing".

I will keep the Debug enabled on in the future, linqcan :-)

**Comment by linqcan** [comment]
Nice find! =)

**Comment by linqcan** [comment]
Closing this now, please test the new version with "Search" and report any issues in a new ticket. Thank you! =)
