### ISSUE TITLE
option for subtitles

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#46]
The plugin (Frodo version) has its own setting for subtitles, why is that? There is already a setting in XBMC to use subtitles or not.
The XBMC setting can be switched while playing which is very convenient.
As it works now, if I want to turn on or off subtitles during playing I have to stop playing, go to context menu, change the setting and restart the video.

**Comment by linqcan** [comment]
The setting merely tells the XBMC player if it should start with the subtitle visible or not.
To toggle the subtitles during playback, use the "T" key on a keyboard or (on ATV2 for example) hack the joystick xml to assign subtitles toggling to a button of choice.

Sources:
http://wiki.xbmc.org/index.php?title=Keyboard
http://wiki.xbmc.org/index.php?title=Alternative_joystick.AppleRemote.xml_for_ATV2
http://wiki.xbmc.org/index.php?title=Apple_remote
https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml#L227

**Comment by kokangit** [comment]
Thanks for the swift reply!
So regardless of the plugin setting I can toggle the subtitles with the usual XBMC setting? I use the setting in the audio menu (on screen menu during play). I will try that this evening.
The ATV2 remote has just 7 buttons, it is hard to motivate having one of those dedicated to subtitle toggling.

**Comment by linqcan** [comment]
I programmed the "up" on ATV2 the remote for toggling subtitles since it does not do much use during playback anyway. Change button id 1 to "ShowSubtitles" for example, in the "FullscreenVideo" section:
https://github.com/xbmc/xbmc/blob/master/system/keymaps/joystick.AppleRemote.xml#L90

**Comment by kokangit** [comment]
Off topic: I like to be able to go back and forward so I programmed up to go forward 10 min, down backward 5 min, right forward 90 s, left backward 30 s. Makes it easy to find a certain point in video.
Thanks anyway!

**Comment by linqcan** [comment]
Aha, fair enough :)

Issue resloved?

**Comment by kokangit** [comment]
Great, now I see that it works to use both settings in a logical way! Problem solved.

**Comment by linqcan** [comment]
Glad I could help :)

Closed.
