### ISSUE TITLE
Bitrate selection not working

### ISSUE THREAD

**Issue by TsUPeR** [kodi-svtplay/xbmc-svtplay#5]
Tried setting bitrate to low and still get the HD stream

**Comment by nilzen** [comment]
Should be fixed in nilzen/xbmc-svtplay@abaf3860f4826646546b

**Comment by TsUPeR** [comment]
Got 
    if (not content and bitrate <= SETTINGS_HIGHEST_BITRATE) or (bitrate > float(content.getAttribute("bitrate")) and bitrate <= SETTINGS_HIGHEST_BITRATE):
    AttributeError: 'NoneType' object has no attribute 'getAttribute'

When going to Program meny senaste > Senaste Program
Bitrate set to low

**Comment by nilzen** [comment]
Fixed now?

**Comment by TsUPeR** [comment]
Yes!
