### ISSUE TITLE
Select quality ... 

### ISSUE THREAD

**Issue by andreasthorn** [kodi-svtplay/xbmc-svtplay#54]
Sometimes SVT servers seems overloaded and viewing in lower quality prevents the show to buffer all the time. Also maybe someone has a bad connection and needs lower quality to be able to view without buffer issues.

I personally have changed the script to use the 2:nd highest quality and generally it works better for me. But changing the script so that the user can select quality from a popup is better.

Today the best resolution is used by default ..

ps. I love the scipt :) I have worked on a program for windows written in .net that scapes the shows from all playt channels in sweden and since moving to openelec/xbmc I miss SVT play .. thanks for suppliing it to us ..

Let med know if there's anything I can do to help :)

**Comment by linqcan** [comment]
SVTPlay is using a format called HLS (as well as Flash) for their video streaming. HLS is distributed as m3u8 files and, ideally, they contain different streams for different bandwidths. However, the content of the m3u8 files varies a lot depending on the content (new, old, SVT produced, licensed etc).
When the XBMC video player is fed a m3u8 file a function is called which determines which version that it should use depending on your (set) bandwidth.

So, the function you are looking for does, more or less, already exists in the system. You just have to set a fixed bandwidth in the XBMC system settings.

Sources:
https://github.com/xbmc/xbmc/blob/master/xbmc/playlists/PlayListM3U.cpp#L184
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/dvdplayer/DVDPlayer.cpp#L566

**Comment by linqcan** [comment]
Additional notes:
Maybe we could implement an internal quality setting to be used on streams which are not handled by XBMC's internal mechanism?
Also, we could offer the possibility to override XBMC's mechanism with our own.

See PR #56 for a use case where this kind of implementation would make sense.

Issue to remain open.

**Comment by linqcan** [comment]
I am sorry, I don't quite follow. Could you explain more what you mean with this comment?

**Comment by TsUPeR** [comment]
Ehh, just disregard my previous comment. I didn't read your comment or the linked code properly :blush:

**Comment by linqcan** [comment]
I have this feature as a WIP locally. No ETA.

**Comment by linqcan** [comment]
If you want to test you can find a working version here: http://github.com/linqcan/xbmc-svtplay/tree/qualityselect

**Comment by linqcan** [comment]
Implemented
