### ISSUE TITLE
Stream/Video stutters

### ISSUE THREAD

**Issue by illithe** [kodi-svtplay/xbmc-svtplay#63]
Videoplayback stutters when played on the Raspberry Pi. Have tried both
latest Raspbmc and OpenElec. Same result.

Works flawless on other systems I tried (Windows or Linux), so the problem 
should be something related to the RPi.

From what I can tell, it does not seem like there is any lack of CPU-power, since
it is about 50% when playing a SVT-stream.

I will gladly supply any other information that will help solve this problem.

**Comment by illithe** [comment]
Sorry, I should have read the old issues before posting a new.
Issue #58 is the same ...

**Comment by linqcan** [comment]
Yes, information is also in the README here on Github:
https://github.com/nilzen/xbmc-svtplay/blob/frodo/README.md
