### ISSUE TITLE
The new section "Kanaler" (Channels) is not available

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#64]
As the title says.

**Comment by linqcan** [comment]
Working on it.

**Comment by linqcan** [comment]
A (working) test can be found here:
https://github.com/linqcan/xbmc-svtplay/tree/channels

Some more polishing (and a final squash) is needed before PR and merge.

**Comment by nilzen** [comment]
Seems to work as expected, merge when you feel comfortable!

**Comment by linqcan** [comment]
Super seeded by #65 , closing.
