### ISSUE TITLE
Fails to start: Urllib2 http error

### ISSUE THREAD

**Issue by Rapio** [kodi-svtplay/xbmc-svtplay#68]
When I start svtplay in xbmc I get text 30600 in a OK dialog. The app worked for a long time then it just stopped one day.

Log-entry:
18:43:47 T:140245077047040  NOTICE: -->Python Interpreter Initialized<--
18:43:49 T:140245077047040   ERROR: Error Type: <class 'urllib2.HTTPError'>
18:43:49 T:140245077047040   ERROR: Error Contents: HTTP Error 404: Not Found
18:43:49 T:140245077047040   ERROR: Traceback (most recent call last):
                                              File "/home/derp/.xbmc/addons/plugin.video.svtplay/default.py", line 450, in <module>
                                                deviceconfiguration()
                                              File "/home/derp/.xbmc/addons/plugin.video.svtplay/default.py", line 53, in deviceconfiguration
                                                node = load_xml("http://svtplay.se/mobil/deviceconfiguration.xml" ).documentElement.getElementsByTagName("body")[0]
                                              File "/home/derp/.xbmc/addons/plugin.video.svtplay/default.py", line 433, in load_xml
                                                raise ex
                                            HTTPError: HTTP Error 404: Not Found
18:43:49 T:140246685988800   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay
18:43:49 T:140246685988800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay) failed

**Comment by linqcan** [comment]
This log is from the old version of the plugin which isn't supported anymore. Upgrade to XBMC 12.0 and install the latest SVT plugin from there.
