### ISSUE TITLE
Stutter on Raspberrry Pi / OpenElec 3 RC4

### ISSUE THREAD

**Issue by JoakimLindbom** [kodi-svtplay/xbmc-svtplay#69]
The plugin works very fine, except the picture is stuttering. There is about 0.5-1 seconds of smooth play, then the stream restarts approx. 0.25 seconds earlier. The actual timing seems to be isochronic as the sound stream is perfect.
I'm running version 3.2.0 of the xbmc-svtplay plugin.

**Comment by nilzen** [comment]
Not a plugin issue, report with full debug log to Xbmc.
