### ISSUE TITLE
Feature request: Continous play/play all episodes

### ISSUE THREAD

**Issue by MattePatte** [kodi-svtplay/xbmc-svtplay#70]
Excellent addon. 

What: 
I'm missing is a setting to automatically queue up all episodes in a series after the episode i have selected. 

How: 
A series contains 5 episodes.
When i start to play episode 2 episode 3, 4 and 5 are automatically queued which enables continous play. 

Why: 
When my daughter wants to see cartoons or similar where all the episodes are 5-10 minutes each this feature would be highly appreciated. :-)

Thanks,
Mattias

**Comment by nilzen** [comment]
This already exists in the context menu?

**Comment by linqcan** [comment]
Hi @MattePatte!

Finally got some time to play with this and created a playlist feature. However, it requries you to manually add the videos.

Add video: Click on "c" to open the context menu for a video to add it (long press "menu" on Apple TV)
Remove from playlist: Open the playlist manager from the top menu. Select a video in the playlist and click on "c" (long press "menu" on Apple TV).
Play: Open the playlist manager from the top menu and then click on "Play".

Only tested this on a HTPC running XBMC 13.

The feature is "beta" at best and can be found here: https://github.com/linqcan/xbmc-svtplay/tree/playlistFeature
It is based on the new code stack and uses SVT beta page and can therefore break at anytime. But I would be really happy if you could test it and drop feedback here! :smile: 

Better late than never I suppose?

cc @nilzen

**Comment by linqcan** [comment]
Zip can be found here (since zips from the GH repo does not work well in XBMC):
https://dl.dropboxusercontent.com/u/9220166/plugin.video.svtplay.zip

Also, it requires XBMC 13 Gotham (http://xbmc.org/xbmc-13-0-gotham-the-beta-2-we-deserve/)

**Comment by linqcan** [comment]
Refactored the whole thing. Latest zip can be found on the link in my previous post. Again, note that it has been developed against the SVT Beta site and XBMC 13.0 Gotham.

**Comment by linqcan** [comment]
Merged in latest release
