### ISSUE TITLE
SVT:s new site "Öppet arkiv" not available via xbmc-svtplay

### ISSUE THREAD

**Issue by ENPark** [kodi-svtplay/xbmc-svtplay#76]
Today SVT launched the new version of "Öppet arkiv", with full runs of classic shows. It does not work in XBMC-SVTPlay (3.3.0) (In fact, I get errors trying to browse "Kategorier"/Categories).
I suppose they changed their feeds. 
The new version of "Öppet arkiv" also has gotten a new site and domain name, which may have something to do with it. The new HTTP address is [http://www.oppetarkiv.se/](http://www.oppetarkiv.se/) I have not looked into how the Atom or RSS looks, but i suppose the new site is not too differently built from the regular play.svt.se.
Question is if "Öppet arkiv" should be a new plug in, based on xbmc-svtplay, or if the latter should include the former. If no technical problems, I would vote for including the new "Öppet arkiv" in xbmc-svtplay.

**Comment by nilzen** [comment]
Since it's on a different domain I would say it qualifies as a new add on... But the question is if @linqcan or me would have time to maintain it...

**Comment by linqcan** [comment]
I am afraid I don't have time to maintain another. Willing to support/coach however.

**Comment by ENPark** [comment]
And I'm a lousy programmer. The script seems understandable enough even for someone like me, with next to no experience in python. 
I suppose I could look into it, but time is a problem for me as well atm (regardless of lacking competence)... 
I hope someone with more wizardlike skills sees this. Me doing it might not be very time-efficient.

**Comment by linqcan** [comment]
And, I agree with @nilzen that this would require a new add on since it is branded as a new service from SVT. Looking at the code it is just a rebranded SVTPlay site and all methods for traversing and video playback will work with minor modifications.

Would suggest just creating an index using this page http://www.oppetarkiv.se/kategori/titel and then use the same viewProgram and startVideo as before.

**Comment by nilzen** [comment]
Same goes for me, to little time to maintain another add on. I don't have enough time for this one so I'm very happy to have @linqcan as my sidekick! :)

@ENPark feel free to fork this code and modify it to a new add on, but only do it if you feel that you have the time to modify it if the site changes. A broken add on is worse than no add on IMO.

**Comment by linqcan** [comment]
+1 on @nilzen's answer. Only do it if you feel like you can do\* it and maintain it.

\* with some support

**Comment by ENPark** [comment]
Thanks for the tips and support @linqcan and @nilzen. I think I'll see if I can get it working in the weekend, and then decide if this is something I can maintain. I'll have forked the code, and will report further!

**Comment by TsUPeR** [comment]
I'm willing to support you @ENPark . Get back with your progress. I have quite a lot of experience in xbmc addon development...

**Comment by ENPark** [comment]
Thanks @TsUPeR, so far I've just had time to scout around the site, which headings they use, things like that. My coding experience is mainly HTML and CSS. Programming has so far been limited to Java- / Ecmasript and some PHP, and then preferably using and modifying variables in other peoples scripts. Not much writing from scratch (never really had to).

**Comment by linqcan** [comment]
@ENPark As mentioned above; you don't have to start from (complete) scratch if you don't want to. The new site is merely a copy of SVTPlay and you can use the some of the functionality (modified) used in the SVTPlay add-on.

**Comment by khoda** [comment]
I've messed around a bit and got all the shows listed( from http://www.oppetarkiv.se/kategori/titel ). Who wants to maintain this? ;)

Edit:
It now plays! 
https://github.com/khoda/xbmc-svtoaplay 

"Show more" pagination is not working. Thus not showing all the episodes. The sites are not quite the same, Öppet Arkiv is missing the data-bindings, no tabs nor clips. There is some work to be done!

@ENPark @TsUPeR

**Comment by khoda** [comment]
Did anyone test it?

**Comment by linqcan** [comment]
@khoda Issues found: "Kategorier" is the same as "Program A-Ö". Other than that (and the missing pagination) it looks fine. Haven't run it in XBMC yet, put it looked OK through my headless tests.

Update: One more thing. Think you should call it svtarchive/svtoa or something. The svtaoplay name is just wrong since the service name is "Öppet Arkiv" (no "Play" there).

**Comment by khoda** [comment]
Cleaned up a bit and added pagination.

Renamed addon to Öppet Arkiv. 

https://github.com/khoda/xbmc-oppetarkiv

**Comment by linqcan** [comment]
Nice, good work!
I will close this ticket now and all questions regarding "Öppet arkiv" should be posted in your tracker.

**Comment by alexbjorling** [comment]
Just want to mention that I've written an addon for Öppet arkiv, it's for my own convenience but I will maintain it.
https://github.com/alexbjorling/kodi-svt-oppetarkiv
