### ISSUE TITLE
HTML in categories

### ISSUE THREAD

**Issue by liftarn** [kodi-svtplay/xbmc-svtplay#89]
If you go into categories the last entry contains HTML code.

**Comment by linqcan** [comment]
Thank you for reporting this issue. I "solved" this by hiding the "Öppetarkiv" item since it doesn't make sense in the plugin anyway to show it.

**Comment by linqcan** [comment]
Sent pull request to XBMC to update the plugin.

**Comment by linqcan** [comment]
The plugin has been updated.
