### ISSUE TITLE
News not updated correctly

### ISSUE THREAD

**Issue by ToddeSwe** [kodi-svtplay/xbmc-svtplay#94]
Hi

I was glad to see the updated version of this add on.
But you might already know this, but i'll tell you anyway. Just to be sure. :)

In all of the news programs listing the news are one day old and the precent days news does not work.

Hope you will fix it 

Thanks for making this

**Comment by linqcan** [comment]
Thank you for reporting the issue!

Please provide the steps required to reproduce this issue. Thank you!

**Comment by ToddeSwe** [comment]
Not much just go to the smålandsnytt, aktuellt or rapport and see for
yourself. 😊
Den 9 jun 2014 07:41 skrev "Erik Lindqvist" notifications@github.com:

**Comment by linqcan** [comment]
I don't get that when I list the videos for "Smålandsnytt". Please provide instructions for how to replicate the issue.

I did the following. "Program A-Ö"->"Smålandsnytt"

**Comment by ToddeSwe** [comment]
When you have browsed to the folder for Smålandsnytt the first/latest news does not work. But this evening it did. so i went to the Rapport news listing and that one did not work. If that depends up on SVT or your add on i din't know. Before this latest recoding or when i stoped working i could see the latest news every time it never failed. But since the last update on SVT service i can't.

**Comment by ToddeSwe** [comment]
Yesterday and the day before it did not even list the latest day just the day before. :)

**Comment by linqcan** [comment]
What is it you are reporting not working? The directory listing and/or playback of video items? You are mentioning both...

**Comment by ToddeSwe** [comment]
Both in some cases, IF there is a new episode of the news it can't be played. And often there's no news at all from the day you are on. God this was hard to explaine. :)

**Comment by linqcan** [comment]
Sorry. I can't recreate this issue at all. I see all videos and they play. 

The next time you have an issue, extract the "xbmc.log" to http://xbmclogs.com and post the link here.

**Comment by ToddeSwe** [comment]
Hi

I will check in again and see, smålandsnytt did work yesterday. I will make a log for you while i'm testing.

**Comment by ToddeSwe** [comment]
Hi

https://db.tt/lWuaovQz

Smålandsnytt is working fine now. Aktuellt and Rapport is not as you might see in the log...

**Comment by linqcan** [comment]
I looked into the error with Rapport and I think the pproblem is that you are trying to play a live stream that is no longer live. Try playing a recorded episode instead. I think it is a glitch in SVT's distribution system where you happen to access a URL just after it went offline (and the cluster hasn't produced the recorded version yet). That would explain the errors I see in your log and why you only see this occasionally.

```
19:49:13 T:1209005152   DEBUG: Error, could not open file http://svt07-lh.akamaihd.net/i/svt07_0@77502/index_6_av-p.m3u8?sd=10&start=1402438800&rebase=on
```

**Comment by ToddeSwe** [comment]
Ok, the listing has started to get better for each day i think. So maybe it will beback as it where in a week or so… :)

Från: Erik Lindqvist [mailto:notifications@github.com] 
Skickat: den 10 juni 2014 21:53
Till: nilzen/xbmc-svtplay
Kopia: ToddeSwe
Ämne: Re: [xbmc-svtplay] News not updated correctly (#94)

I looked into the error with Rapport and I think the pproblem is that you are trying to play a live stream that is no longer live. Try playing a recorded episode instead. I think it is a glitch in SVT's distribution system where you happen to access a URL just after it went offline (and the cluster hasn't produced the recorded version yet).

19:49:13 T:1209005152   DEBUG: Error, could not open file  http://svt07-lh.akamaihd.net/i/svt07_0@77502/index_6_av-p.m3u8?sd=10&start=1402438800&rebase=on http://svt07-lh.akamaihd.net/i/svt07_0@77502/index_6_av-p.m3u8?sd=10&start=1402438800&rebase=on

**Comment by linqcan** [comment]
Closing this for now as I believe that this is not a addon issue. Will re-open if new evidence shows otherwise.
