### ISSUE TITLE
Channels and some live broadcasts not working on atv2

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#98]

**Comment by linqcan** [comment]
This cannot be fixed by the addon. It is broken by design for some platforms, iOS being one of them:
http://forum.xbmc.org/showthread.php?tid=166897&page=3
http://forum.xbmc.org/showthread.php?tid=189621

**Comment by linqcan** [comment]
Not going to change anytime soon. http://forum.xbmc.org/showthread.php?tid=166897&pid=1745183#pid1745183

Might need to find a way to disable playback of "https" streams on iOS/OSX etc.

**Comment by linqcan** [comment]
Unsupported platforms for live streams are: iOS, ATV2, OSX and Android.

**Comment by linqcan** [comment]
Should work as a guard:

```
xbmc.getCondVisibility('System.Platform.OSX | System.Platform.ATV2 | System.Platform.IOS | System.Platform.Android ')
```

**Comment by niklask** [comment]
I find this interesting. I have been using Kodi 15/16 on my Nvidia Shield TV running Android for a few weeks without any problems watching channels live until yesterday when they suddenly disappeared from the menu. Is that related to encrypted streams or is there another bug in the SVTplay addon causing this?

**Comment by linqcan** [comment]
Neither, probably SVT changing the structure of their site. I will have a
look.

**Comment by niklask** [comment]
It was neither. The channels came back on Friday.

**Comment by linqcan** [comment]
Great! 👍

**Comment by linqcan** [comment]
HTTPS streaming should be enabled on all platforms now (since 2015-06):
http://forum.kodi.tv/showthread.php?tid=166897&page=4

Hence the closing of this issue.
